//! Tool-schema and tool-call/result types.

use serde::{Deserialize, Serialize};

use crate::domain::AttachmentInfo;

// =============================================================================
// Tool schema
// =============================================================================

/// A tool that the LLM may invoke, expressed as a name + JSON Schema.
///
/// This is the agent domain's own type. Adapter layers are responsible for
/// converting their internal tool representations:
///
/// - MCP adapter: `McpTool → ToolDefinition`
/// - Built-in tools: constructed directly
///
/// The agent domain must **not** reference `McpTool` or any crate-external
/// tool type directly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// Unique function name exposed to the LLM (e.g. `"filesystem_read_file"`).
    pub name: String,

    /// Human-readable description sent to the LLM to explain when to use the tool.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// JSON Schema object describing the tool's input parameters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_schema: Option<serde_json::Value>,

    /// Human-readable display title from MCP `annotations.title`.
    ///
    /// When present, surfaces prefer this over the heuristic
    /// `format_tool_display_name()`.  Not serialized to the LLM.
    #[serde(skip)]
    pub title: Option<String>,
}

impl ToolDefinition {
    /// Create a minimal tool definition with only a name.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            input_schema: None,
            title: None,
        }
    }

    /// Attach a human-readable description.
    #[must_use]
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Attach a JSON Schema for the tool's input parameters.
    #[must_use]
    pub fn with_input_schema(mut self, schema: serde_json::Value) -> Self {
        self.input_schema = Some(schema);
        self
    }
}

// =============================================================================
// Tool call / result
// =============================================================================

/// A tool invocation requested by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS), ts(export))]
pub struct ToolCall {
    /// Unique identifier for this call, generated by the LLM.
    ///
    /// Must be echoed back in the corresponding [`ToolResult::tool_call_id`].
    pub id: String,

    /// Name of the tool to invoke (matches [`ToolDefinition::name`]).
    pub name: String,

    /// Arguments as a JSON object, matching the tool's `input_schema`.
    ///
    /// Typed rather than left to ts-rs, which has no `TS` for
    /// `serde_json::Value` without its `serde-json-impl` feature. `Record` is
    /// also the truer answer: the shape is whatever the tool's own schema
    /// says, which gglib does not model.
    #[cfg_attr(feature = "ts-bindings", ts(type = "Record<string, unknown>"))]
    pub arguments: serde_json::Value,
}

/// The outcome of executing a [`ToolCall`].
///
/// # Important: failures are context, not errors
///
/// A `ToolResult` with `success: false` is **not** a Rust-level error —
/// it is domain data that gets appended to the conversation as an
/// `AgentMessage::Tool` entry so the model can observe the failure and
/// adjust its strategy (retry, fix arguments, use a different tool, etc.).
///
/// Infrastructure-level failures (e.g. the MCP process crashed) are
/// surfaced separately via `anyhow::Error` from [`crate::ports::ToolExecutorPort::execute`]
/// and then converted by the loop implementation into a `ToolResult` with
/// `success: false` and an appropriate `content` describing the outage.
///
/// # Images go to the conversation, not the model
///
/// A tool that makes images stores them and lists them in [`Self::images`].
/// They are saved on the result's tool row and shown to the user; the model
/// reads only [`Self::content`], so the tool names each image there in words.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS), ts(export))]
pub struct ToolResult {
    /// Echoes the [`ToolCall::id`] this result corresponds to.
    pub tool_call_id: String,

    /// Human-readable output (or error message) from the tool execution.
    pub content: String,

    /// Whether the tool completed successfully.
    ///
    /// `false` here is **not** a loop error — see type-level docs above.
    pub success: bool,

    /// The images the tool made, stored, in the order it returned them.
    /// Left out of the JSON when there are none and read as none when
    /// absent, so a frame logged without the field still parses.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    #[cfg_attr(
        feature = "ts-bindings",
        ts(as = "Option<Vec<AttachmentInfo>>", optional)
    )]
    pub images: Vec<AttachmentInfo>,
}

impl ToolResult {
    /// A result whose whole output is `content`, with no images.
    #[must_use]
    pub fn text(
        tool_call_id: impl Into<String>,
        content: impl Into<String>,
        success: bool,
    ) -> Self {
        Self {
            tool_call_id: tool_call_id.into(),
            content: content.into(),
            success,
            images: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn tool_definition_builder_sets_fields() {
        let tool = ToolDefinition::new("search")
            .with_description("Full-text search")
            .with_input_schema(json!({ "type": "object" }));
        assert_eq!(tool.name, "search");
        assert!(tool.description.is_some());
        assert!(tool.input_schema.is_some());
    }

    #[test]
    fn tool_result_success_false_is_serialisable() {
        let result = ToolResult::text("c1", "ERROR: file not found", false);
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(json["success"], false);
        assert!(
            json.get("wait_ms").is_none(),
            "wait_ms must not be on ToolResult"
        );
        assert!(
            json.get("execute_duration_ms").is_none(),
            "execute_duration_ms must not be on ToolResult"
        );
    }

    #[test]
    fn a_result_without_images_is_the_frame_it_always_was() {
        let result = ToolResult::text("c1", "fn main() {}", true);
        assert_eq!(
            serde_json::to_string(&result).unwrap(),
            r#"{"tool_call_id":"c1","content":"fn main() {}","success":true}"#
        );
        let old: ToolResult =
            serde_json::from_str(r#"{"tool_call_id":"c1","content":"x","success":false}"#).unwrap();
        assert!(old.images.is_empty());
    }

    #[test]
    fn a_result_with_images_carries_them_and_reads_back() {
        let image = AttachmentInfo {
            id: crate::domain::AttachmentId::of(b"png"),
            mime: "image/png".to_owned(),
            width: 2,
            height: 3,
        };
        let mut result = ToolResult::text("c1", "[image 2x3 PNG stored]", true);
        result.images = vec![image.clone()];
        let json = serde_json::to_value(&result).unwrap();
        assert_eq!(
            json["images"],
            json!([{ "id": image.id.as_str(), "mime": "image/png", "width": 2, "height": 3 }])
        );
        let back: ToolResult = serde_json::from_value(json).unwrap();
        assert_eq!(back.images, vec![image]);
    }
}
