//! Port trait for the orchestrator approval registry.
//!
//! The approval registry is a **process-local** store that pairs an
//! `approval_id` with a `tokio::oneshot::Sender<ApprovalDecision>`.  When the
//! executor reaches a HITL gate it:
//!
//! 1. Creates a oneshot channel and calls [`CouncilApprovalRegistryPort::register`]
//!    with the sender.
//! 2. Emits [`crate::domain::council::events::CouncilEvent::AwaitingApproval`]
//!    carrying the `approval_id`.
//! 3. Awaits the receiver.
//!
//! An external actor (the Axum handler or the CLI prompter) retrieves and
//! resolves the decision by calling
//! [`CouncilApprovalRegistryPort::resolve`].

use async_trait::async_trait;
use tokio::sync::oneshot;

use crate::domain::council::task_graph::TaskGraph;

// =============================================================================
// ApprovalDecision
// =============================================================================

/// The decision a human makes at a HITL gate.
#[derive(Debug)]
pub enum ApprovalDecision {
    /// Proceed as-is.
    Approve,
    /// Proceed with a user-supplied modified graph.
    ///
    /// Only meaningful for `Plan` gates; for `Node` / `Tool` gates the
    /// executor ignores the graph and treats this as a plain `Approve`.
    ApproveWithEdits(Box<TaskGraph>),
    /// Reject and terminate the run.
    Reject(String),
}

// =============================================================================
// CouncilApprovalRegistryPort
// =============================================================================

/// Process-local store for pending HITL approval requests.
///
/// Implementations MUST be `Send + Sync + 'static` so the registry can be
/// shared across the Axum router, spawned executor tasks, and CLI prompts.
///
/// # Acknowledged limitation
///
/// The registry is intentionally **process-local** in v1.  Cross-process
/// approval coordination (e.g. multiple server instances) is out of scope.
#[async_trait]
pub trait CouncilApprovalRegistryPort: Send + Sync + 'static {
    /// Register a pending approval gate.
    ///
    /// The `approval_id` is a UUID v4 string generated by the executor.
    /// The `sender` will be consumed by the next `resolve()` call with
    /// the same id.
    fn register(&self, approval_id: String, sender: oneshot::Sender<ApprovalDecision>);

    /// Resolve a pending approval gate.
    ///
    /// Removes the entry keyed by `approval_id` from the registry and sends
    /// `decision` on the stored oneshot channel.
    ///
    /// Returns `true` if the approval existed and was resolved, `false` if
    /// the id was not found (e.g. the run already completed or the sender was
    /// dropped).
    fn resolve(&self, approval_id: &str, decision: ApprovalDecision) -> bool;

    /// Returns `true` if an approval with the given id is currently pending.
    fn is_pending(&self, approval_id: &str) -> bool;
}
