#![doc = include_str!("README.md")]
pub mod agent;
pub mod benchmark;
pub mod builtin;
pub mod chat;
pub mod config;
pub mod council;
pub mod events;
pub mod mcp;
pub mod model;
pub mod port_utils;
pub mod proxy;
pub mod servers;
