#![doc = include_str!("README.md")]
pub(crate) mod agent;
pub(crate) mod attachments;
pub(crate) mod benchmark;
pub(crate) mod builtin;
pub(crate) mod chat_title;
pub(crate) mod config;
pub(crate) mod daemon;
pub(crate) mod events;
pub(crate) mod generation;
pub(crate) mod images;
pub(crate) mod mcp;
pub(crate) mod model;
pub(crate) mod port_utils;
pub(crate) mod proxy;
pub(crate) mod remote;
pub(crate) mod runs;
pub(crate) mod servers;
pub(crate) mod version;
