// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What acceleration a build would use.
 *
 * Detection is deliberately fallible — it refuses to fall back to CPU so
 * callers can surface install hints — so the failure is carried as data
 * rather than failing the whole diagnostics request.
 */
export type AccelerationDto = { detected: string | null, detectionError: string | null, };
