// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for adding a tag via POST to /api/models/{id}/tags
 */
export type AddTagRequest = { tag: string, };
