// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing configuration for a single agent chat request.
 *
 * Exposes only the fields that are safe to accept from an untrusted HTTP
 * caller. Internal tuning parameters (`prune_*`, `max_repeated_batch_steps`,
 * `context_budget_chars`, etc.) are intentionally absent — they default to
 * their well-tested values and cannot be weaponised to exhaust server
 * resources.
 *
 * All numeric fields are clamped server-side to the ceiling constants defined
 * in [`gglib_core::domain::agent::config`] to prevent resource exhaustion.
 *
 * # Observation-tool fields
 *
 * `observation_tools` and `max_observation_steps` are intentionally exposed
 * to callers because gglib is a BYO-MCP platform: users may connect arbitrary
 * MCP servers whose tool names are unknown at compile time.  Callers that want
 * to classify a custom tool as observation-only (and therefore subject to the
 * higher repetition threshold) should pass its name fragment here.
 */
export type AgentRequestConfig = { 
/**
 * Maximum number of LLM→tool→LLM iterations.
 * Clamped to [`MAX_ITERATIONS_CEILING`](gglib_core::domain::agent::config::MAX_ITERATIONS_CEILING)
 * server-side.
 */
max_iterations: number | null, 
/**
 * Maximum number of tool calls dispatched in parallel per iteration.
 * Clamped to [`MAX_PARALLEL_TOOLS_CEILING`](gglib_core::domain::agent::config::MAX_PARALLEL_TOOLS_CEILING)
 * server-side.
 */
max_parallel_tools: number | null, 
/**
 * Per-tool execution timeout in milliseconds.
 * Clamped to [`MAX_TOOL_TIMEOUT_MS_CEILING`](gglib_core::domain::agent::config::MAX_TOOL_TIMEOUT_MS_CEILING)
 * server-side.
 */
tool_timeout_ms: number | null, 
/**
 * Substring/suffix patterns that classify a tool as observation-only.
 *
 * When **every** call in a batch matches a pattern, the higher
 * `max_observation_steps` threshold is applied instead of the standard
 * loop-detection threshold.  Matching is case-insensitive and uses
 * `ends_with` OR `contains` semantics.
 *
 * `Some([])` disables observation classification entirely.
 * `None` (field absent) keeps the built-in defaults, which cover
 * browser tools and the read-only tools coding agents repeat — see
 * `AgentConfig::default`.
 */
observation_tools: Array<string> | null, 
/**
 * Maximum repetitions of an observation-only batch **that keeps getting
 * the same answer back** before loop detection fires.
 *
 * A repeat whose answer changed is not counted at all: the same call with
 * a different result is an agent polling for output, not a loop.
 *
 * This value is read twice. For a batch that is **not** observation-only
 * it is never the strike threshold, but it *is* the ceiling on how far
 * changing answers may carry that batch — otherwise any tool whose output
 * carries a clock would be exempt from the guard entirely. Raising this
 * therefore loosens the guard for every batch, not only read-only ones.
 *
 * Clamped to `MAX_OBSERVATION_STEPS_CEILING` (100) server-side.
 * `None` (field absent) keeps the built-in default of `15`.
 */
max_observation_steps: number | null, };
