// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * A single message in the agent conversation.
 *
 * The closed enum prevents invalid states that a flat struct with `role: String`
 * would allow (e.g. a `User` message carrying `tool_calls`, or a `Tool` message
 * without a `tool_call_id`).
 *
 * # Wire format
 *
 * `#[serde(tag = "role", rename_all = "lowercase")]` produces JSON identical to
 * the TypeScript `ChatMessage` interface in the frontend:
 *
 * ```json
 * { "role": "user", "content": "What files are in the project?" }
 * { "role": "assistant", "content": null, "tool_calls": [...] }
 * { "role": "tool", "tool_call_id": "call_abc", "content": "src/\nlib/" }
 * ```
 */
export type AgentMessage = { "role": "system", 
/**
 * Instruction text.
 */
content: string, } | { "role": "user", 
/**
 * Message text.
 */
content: string, } | { "role": "assistant", 
/**
 * Optional text content from the model.  `None` when the model produced
 * only tool calls with no text preamble.
 *
 * Both annotations below restate what [`super::messages_serde`]'s
 * hand-written impls do, because ts-rs reads *fields* and cannot see a
 * manual `Serialize`. Without them the binding claims a `text` key that
 * no payload has ever carried. The table above is the contract.
 */
content?: string, 
/**
 * Tool calls requested by the model.  Empty when the model produced a
 * text-only response (final answer).
 *
 * `as Option<…>` because the impl omits the key entirely for an empty
 * vec, which is a state a bare `Vec` cannot express in TypeScript.
 */
tool_calls?: Array<ToolCall>, } | { "role": "tool", 
/**
 * Must match the [`ToolCall::id`] from the preceding `Assistant` message.
 */
tool_call_id: string, 
/**
 * Serialised output of the tool (or error description if it failed).
 */
content: string, };
