// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for calling an MCP tool (includes server ID).
 */
export type CallToolRequest = { server_id: number, tool_name: string, 
/**
 * Tool arguments, shaped by the tool's own schema and opaque here.
 */
arguments: Record<string, unknown>, };
