// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a tune candidate's sampling settings came from.
 */
export type CandidateSource = { "kind": "user_grid" } | { "kind": "family_preset", 
/**
 * Display name of the matched family/preset (e.g. `"qwen-coding"`).
 */
family: string, } | { "kind": "incumbent" } | { "kind": "incumbent_calibration" };
