// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ReasoningEffort } from "./ReasoningEffort";

/**
 * Request body for chat completion proxy.
 */
export type ChatProxyRequest = { 
/**
 * The port of the llama-server to forward to.
 */
port: number, 
/**
 * The model identifier (not used for routing, just forwarded).
 */
model: string, 
/**
 * The messages to send.
 */
messages: Array<ChatMessage>, 
/**
 * Whether to stream the response.
 */
stream: boolean, 
/**
 * Optional max tokens (inference parameter - will be resolved via hierarchy).
 */
maxTokens: number | null, 
/**
 * Optional temperature (inference parameter - will be resolved via hierarchy).
 */
temperature: number | null, 
/**
 * Optional top_p (inference parameter - will be resolved via hierarchy).
 */
topP: number | null, 
/**
 * Optional top_k (inference parameter - will be resolved via hierarchy).
 */
topK: number | null, 
/**
 * Optional repeat_penalty (inference parameter - will be resolved via hierarchy).
 */
repeatPenalty: number | null, 
/**
 * Optional presence_penalty (inference parameter - will be resolved via hierarchy).
 */
presencePenalty: number | null, 
/**
 * Optional min_p sampling threshold (inference parameter - will be resolved via hierarchy).
 */
minP: number | null, 
/**
 * How hard to ask the model to think, where its chat template reads the
 * variable (inference parameter - will be resolved via hierarchy).
 *
 * Conditional by nature: a template that does not read `reasoning_effort`
 * ignores it in silence, and gglib deletes the key rather than sending it
 * on a model whose observed caps say so (ADR 0007 decision 3). A client
 * that wants a promise the template cannot break wants
 * [`Self::reasoning_budget_tokens`], which llama.cpp enforces sampler-side.
 *
 * No `none` level is offered here or anywhere else in gglib: erasing the
 * kwarg yields the template's own default, which is a different act from
 * naming a level, and is what omitting this field already does.
 */
reasoningEffort: ReasoningEffort | null, 
/**
 * Ceiling on this turn's thinking tokens (inference parameter - will be
 * resolved via hierarchy).
 *
 * `-1` defers to the launch-time default; `0` stops thinking altogether.
 * Upstream range-validates it, so a value gglib forwards and llama-server
 * dislikes comes back as an honest HTTP 400 naming the range.
 */
reasoningBudgetTokens: number | null, 
/**
 * Optional tools for function calling.
 *
 * Forwarded to llama-server untouched, so gglib models no shape here and
 * TypeScript says so: `unknown[]`, not a guessed `Tool` interface.
 */
tools: unknown[] | null, 
/**
 * Optional tool choice strategy.
 */
toolChoice: unknown | null, };
