// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One dependency's state.
 *
 * `status` is flattened to a string plus an optional version rather than an
 * externally-tagged enum: the GUI switches on three cases and the extra
 * nesting buys nothing.
 */
export type DependencyDto = { name: string, 
/**
 * `"present" | "missing" | "optional"`.
 */
status: string, 
/**
 * Present only when `status` is `"present"`.
 */
version: string | null, description: string, required: boolean, installHint: string | null, };
