// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for `GET /api/models/{id}/explain`.
 */
export type ExplainQueryParams = { 
/**
 * Name of a configured inference profile to apply on top of the model's
 * own defaults. An unknown name is a 400 listing the configured ones,
 * not a silent fall back to the unprofiled resolution.
 */
profile: string | null, };
