// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BenchmarkRun } from "./BenchmarkRun";

/**
 * Response body for `GET /api/benchmark/runs/{id}`.
 */
export type GetRunResponse = { run: BenchmarkRun, };
