// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The field to sort the model list by.
 */
export type ModelSortBy = "added_at" | "name" | "param_count" | "latest_tg_tps";
