// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proxy status response.
 * Matches Tauri's `ProxyStatus` for frontend compatibility.
 */
export type ProxyStatus = { running: boolean, port: number | null, current_model: string | null, model_port: number | null, 
/**
 * The model this proxy run is pinned to, when started in pinned mode
 * (`gglib serve`). `None` for the ordinary auto-swapping proxy.
 */
pinned_model: string | null, };
