// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from queue_download.
 * Canonical shape returned to all clients - never a tuple.
 */
export type QueueDownloadResponse = { 
/**
 * Position in the queue (0 = downloading now).
 */
position: number, 
/**
 * Number of shards queued (1 for single file, N for sharded models).
 */
shard_count: number, };
