// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A hardware-sized model suggestion — what `gglib up` picks on a first run.
 *
 * `null` from the route rather than an empty object when nothing fits: "no
 * model in the shortlist fits this machine" is a real answer and the UI has
 * to say so, not show a recommendation card with blanks in it.
 */
export type RecommendationDto = { repo: string, quantization: string, 
/**
 * Why this model, in the user's terms.
 */
rationale: string, 
/**
 * Weights plus KV cache at the candidate's context, at the quantization
 * the runtime actually launches with.
 */
requiredBytes: number, 
/**
 * The memory figure it was sized against.
 */
budgetBytes: number, 
/**
 * Where that figure came from: `"vram" | "unifiedMemory" | "systemRam"`.
 */
budgetSource: string, headroomBytes: number, context: number, };
