// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The connect side, while it is up.
 */
export type RemoteConnection = { 
/**
 * The loopback port bound here.
 */
port: number, 
/**
 * `http://127.0.0.1:<port>/v1`.
 */
base_url: string, 
/**
 * Fingerprint of the ticket dialled.
 */
ticket_fingerprint: string, 
/**
 * How this side is reaching the peer: `idle`, `direct`, `relayed`.
 */
path: string, 
/**
 * Seconds the far machine has been away, or `None` while it is here.
 * The port stays bound either way.
 */
away_for_s: number | null, };
