// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to reorder a single download.
 */
export type ReorderRequest = { model_id: string, position: number, };
