// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardHealth } from "./ShardHealth";

/**
 * Health report for a single shard.
 */
export type ShardHealthReport = { 
/**
 * Shard index.
 */
index: number, 
/**
 * File path.
 */
file_path: string, 
/**
 * Health status.
 */
health: ShardHealth, };
