// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System memory information DTO for HTTP API.
 *
 * This DTO ensures stable JSON field names (camelCase) for frontend consumption.
 * Uses the memory field most useful for model fit calculations.
 */
export type SystemMemoryInfoDto = { 
/**
 * Total system RAM in bytes.
 */
totalRamBytes: number, 
/**
 * GPU memory in bytes: VRAM on a discrete card, or the addressable share
 * of host RAM on a unified-memory device. None if it could not be read.
 */
gpuMemoryBytes?: number, 
/**
 * Whether the GPU shares host memory — Apple Silicon or an integrated GPU.
 */
isUnifiedMemory: boolean, 
/**
 * Whether the system has an NVIDIA GPU.
 */
hasNvidiaGpu: boolean, };
