// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for updating a message.
 */
export type UpdateMessageRequest = { content: string, metadata: unknown | null, };
