// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShardUpdate } from "./ShardUpdate";

/**
 * Details about available updates.
 */
export type UpdateDetails = { 
/**
 * Number of shards that have changed.
 */
changed_shards: number, 
/**
 * OID changes per shard.
 */
changes: Array<ShardUpdate>, };
