// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverallHealth } from "./OverallHealth";
import type { ShardHealthReport } from "./ShardHealthReport";

/**
 * Complete verification report for a model.
 */
export type VerificationReport = { 
/**
 * Model ID that was verified.
 */
model_id: number, 
/**
 * Overall health status.
 */
overall_health: OverallHealth, 
/**
 * Health status for each shard.
 */
shards: Array<ShardHealthReport>, 
/**
 * When the verification was performed.
 */
verified_at: string, };
