/**
 * Agent SSE event types — mirrors `gglib_core::domain::agent::AgentEvent`.
 *
 * Each variant is tagged with a `type` field using snake_case, matching the
 * Rust `#[serde(tag = "type", rename_all = "snake_case")]` annotation.
 *
 * @module agentEvent
 */

// ---------------------------------------------------------------------------
// Embedded wire types (mirror Rust ToolCall / ToolResult)
// ---------------------------------------------------------------------------

/** A tool invocation requested by the LLM (mirrors `gglib_core::ToolCall`). */
export interface AgentToolCall {
  /** Unique identifier generated by the LLM; echoed back in the result. */
  id: string;
  /** Tool name (matches the registered tool definition). */
  name: string;
  /** Arguments as a parsed JSON object. */
  arguments: unknown;
}

/** The outcome of a tool execution (mirrors `gglib_core::ToolResult`). */
export interface AgentToolResult {
  /** Echoes the `AgentToolCall.id` this result belongs to. */
  tool_call_id: string;
  /** Human-readable output or error description from the tool. */
  content: string;
  /** `false` here is **not** an error — it is context fed to the LLM. */
  success: boolean;
}

// ---------------------------------------------------------------------------
// Discriminated union
// ---------------------------------------------------------------------------

/** An incremental text fragment from the model's response. */
export interface AgentTextDeltaEvent {
  type: 'text_delta';
  content: string;
}

/** The model has requested execution of a tool. */
export interface AgentToolCallStartEvent {
  type: 'tool_call_start';
  tool_call: AgentToolCall;
  /** Human-readable title-cased tool name (e.g. "Read File"). */
  display_name: string;
  /** Optional one-line argument summary (e.g. a file path). */
  args_summary?: string;
}

/** A tool execution has completed (success or failure). */
export interface AgentToolCallCompleteEvent {
  type: 'tool_call_complete';
  /** Raw tool name including any prefix (e.g. "builtin:read_file"). */
  tool_name: string;
  result: AgentToolResult;
  /** Time spent waiting for a concurrency slot, in milliseconds. */
  wait_ms: number;
  /** Wall-clock execution time (after acquiring the slot), in milliseconds. */
  execute_duration_ms: number;
  /** Human-readable title-cased tool name (e.g. "Read File"). */
  display_name: string;
  /** Pre-formatted duration string (e.g. "125ms", "1.8s"). */
  duration_display: string;
}

/** One full LLM → tool-execution cycle has completed. */
export interface AgentIterationCompleteEvent {
  type: 'iteration_complete';
  /** 1-based iteration index that just finished. */
  iteration: number;
  /** Number of tool calls executed during this iteration. */
  tool_calls: number;
}

/**
 * An incremental reasoning/thinking fragment (CoT tokens).
 *
 * Emitted by reasoning-capable models (e.g. DeepSeek R1, QwQ) that expose
 * their chain-of-thought.  These tokens are forwarded live but are excluded
 * from the conversation history sent back to the model.
 */
export interface AgentReasoningDeltaEvent {
  type: 'reasoning_delta';
  content: string;
}

/** The loop has concluded and produced a definitive answer. */
export interface AgentFinalAnswerEvent {
  type: 'final_answer';
  content: string;
}

/** A fatal error has terminated the loop. */
export interface AgentErrorEvent {
  type: 'error';
  message: string;
}

/** Prompt pre-fill progress from the LLM backend. */
export interface AgentPromptProgressEvent {
  type: 'prompt_progress';
  processed: number;
  total: number;
  cached: number;
  time_ms: number;
}

/**
 * Union of all events emitted by the backend agentic loop over SSE.
 *
 * Consumers should handle all variants; unknown `type` values should be
 * ignored to remain forward-compatible with new variants added on the server.
 */
export type AgentEvent =
  | AgentTextDeltaEvent
  | AgentReasoningDeltaEvent
  | AgentToolCallStartEvent
  | AgentToolCallCompleteEvent
  | AgentIterationCompleteEvent
  | AgentFinalAnswerEvent
  | AgentErrorEvent
  | AgentPromptProgressEvent;
