// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceConfig } from "./InferenceConfig";
import type { InferenceProfile } from "./InferenceProfile";

/**
 * Application settings for the settings UI.
 *
 * `Default` is "nothing configured" — every field is optional, so it stands
 * for a fresh install with no saved values, which is what callers resolving
 * their own fallbacks need to test against.
 */
export type AppSettings = { defaultDownloadPath: string | null, defaultContextSize: number | null, proxyPort: number | null, llamaBasePort: number | null, maxDownloadQueueSize: number | null, showMemoryFitIndicators: boolean | null, maxToolIterations: number | null, maxStagnationSteps: number | null, 
/**
 * Default model ID for quick commands (e.g., `gglib question`).
 */
defaultModelId: number | null, inferenceDefaults: InferenceConfig | null, 
/**
 * Named sampling profiles, selectable per request as `{model}:{profile}`.
 */
inferenceProfiles: Array<InferenceProfile> | null, setupCompleted: boolean | null, titleGenerationPrompt: string | null, bindHost: string | null, shareLan: boolean | null, proxyApiKey: string | null, trustClientSampling: boolean | null, proxyLoopDetection: boolean | null, 
/**
 * Whether a tool call failing schema validation is re-issued with
 * `tool_choice: "required"`. Absent means on.
 */
toolCallRepair: boolean | null, 
/**
 * Whether structured-output turns get their temperature capped when no
 * human chose one. Absent means on (see `gglib_core::Settings`). Was
 * write-only until the GUI grew a toggle — a toggle that saves but
 * cannot read back silently resets on every reopen.
 */
agenticSampling: boolean | null, proxyAutostart: boolean | null, closeToTray: boolean | null, startAtLogin: boolean | null, };
