// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpEnvEntryDto } from "./McpEnvEntryDto";
import type { McpLifecycle } from "./McpLifecycle";

/**
 * Request to create a new MCP server.
 */
export type CreateMcpServerRequest = { name: string, server_type: string, command: string | null, args: Array<string>, working_dir: string | null, path_extra: string | null, url: string | null, env: Array<McpEnvEntryDto>, lifecycle: McpLifecycle, };
