// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HfQuantization } from "./HfQuantization";

/**
 * Response containing available quantizations for a model.
 */
export type HfQuantizationsResponse = { model_id: string, quantizations: Array<HfQuantization>, };
