// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a specific quantization variant.
 */
export type HfQuantization = { name: string, file_path: string, size_bytes: number, size_mb: number, is_sharded: boolean, shard_count: number | null, };
