// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";

/**
 * Inference parameters for LLM sampling.
 *
 * All fields are optional to support partial configuration and fallback chains.
 * Intended to be shared across model defaults, global settings, and request overrides.
 *
 * # Hierarchy Resolution
 *
 * When making an inference request, parameters are resolved in this order:
 * 1. Request-level override (user specified for this request)
 * 2. Selected profile (`Settings.inference_profiles`, chosen as
 *    `{model}:{profile}`; absent on surfaces without profiles)
 * 3. Per-model defaults (stored in `Model.inference_defaults`)
 * 4. Global settings (stored in `Settings.inference_defaults`)
 * 5. Hardcoded fallback (e.g., temperature = 0.7)
 *
 * # Examples
 *
 * ```rust
 * use gglib_core::domain::InferenceConfig;
 *
 * // Conservative settings for code generation
 * let code_gen = InferenceConfig {
 *     temperature: Some(0.2),
 *     top_p: Some(0.9),
 *     top_k: Some(40),
 *     max_tokens: Some(2048),
 *     repeat_penalty: Some(1.1),
 *     ..Default::default()
 * };
 *
 * // Creative writing settings
 * let creative = InferenceConfig {
 *     temperature: Some(1.2),
 *     top_p: Some(0.95),
 *     ..Default::default()
 * };
 * ```
 */
export type InferenceConfig = { 
/**
 * Sampling temperature (0.0 - 2.0).
 *
 * Controls randomness in token selection:
 * - Lower values (0.1-0.5): More deterministic, focused
 * - Medium values (0.7-1.0): Balanced creativity
 * - Higher values (1.1-2.0): More random, creative
 */
temperature: number | null, 
/**
 * Nucleus sampling threshold (0.0 - 1.0).
 *
 * Considers only the top tokens whose cumulative probability exceeds this threshold.
 * Common values: 0.9 (default), 0.95 (more diverse)
 */
topP: number | null, 
/**
 * Top-K sampling limit.
 *
 * Considers only the K most likely next tokens.
 * Common values: 40 (default), 10 (focused), 100 (diverse)
 */
topK: number | null, 
/**
 * Maximum tokens to generate in response.
 *
 * Hard limit on response length. Does not include input tokens.
 */
maxTokens: number | null, 
/**
 * Repetition penalty (> 0.0, typically 1.0 - 1.3).
 *
 * Penalizes repeated tokens to reduce repetitive output.
 * - 1.0: No penalty (default)
 * - 1.1-1.3: Moderate penalty
 * - > 1.3: Strong penalty (may hurt coherence)
 */
repeatPenalty: number | null, 
/**
 * Presence penalty (0.0 - 2.0).
 *
 * Penalizes tokens that have already appeared in the output, encouraging
 * the model to cover new ground. Effective at preventing repetitive
 * reasoning loops in thinking models.
 * - 0.0: No penalty (default; disabled)
 * - 1.5: Recommended for reasoning/thinking models (e.g. `Qwen3.6`, `DeepSeek-R1`)
 * - > 2.0: Avoid; may degrade coherence
 */
presencePenalty: number | null, 
/**
 * Frequency penalty (-2.0 - 2.0), `presence_penalty`'s twin.
 *
 * Penalizes tokens in proportion to how *often* they have already
 * appeared, where `presence_penalty` is a flat once-seen offset. An
 * OpenAI-standard field that llama.cpp supports; until it was modelled
 * here it passed through the proxy ungoverned, so an untrusted client
 * could steer sampling with it while every modelled twin was gated
 * (ADR 0003's `frequency_penalty` follow-up).
 * - 0.0: No penalty (llama.cpp's default)
 * - Negative values *encourage* reuse; valid upstream, rarely wanted
 *
 * Unset defers to llama.cpp's own default (0.0, disabled).
 *
 * Deliberately **not** part of the temperature-coupled trio, although
 * the trio's rationale (a flat logit offset competing with temperature's
 * sharpening) applies to it literally. The cost that evicted DRY from
 * the coupled set (#746) applies literally too: coupling would make a
 * layer naming only a `frequency_penalty` lose it to any lower layer
 * naming a `temperature` — the default state of every `reasoning`-tagged
 * model — and no shipped profile pairs a frequency penalty with a
 * temperature, so coupling would protect nothing in exchange. The trio
 * stays a closed set; joining it needs sweep data, not symmetry.
 */
frequencyPenalty: number | null, 
/**
 * Minimum-probability sampling threshold (0.0 - 1.0).
 *
 * Removes tokens whose probability is below `min_p × P(top token)`.
 * - 0.0: Disabled (explicit off; recommended by Qwen3.6, and the floor
 *   for `reasoning`-tagged models — see [`reasoning_floor`])
 * - 0.05: llama.cpp's own default, and the neutral floor here — see
 *   [`with_hardcoded_defaults`]
 *
 * [`reasoning_floor`]: Self::reasoning_floor
 * [`with_hardcoded_defaults`]: Self::with_hardcoded_defaults
 */
minP: number | null, 
/**
 * Dynamic-temperature half-range — entropy-adaptive temperature.
 *
 * llama.cpp scales the effective temperature within
 * `[temperature − range, temperature + range]` by the entropy of each
 * step's token distribution: confident (low-entropy) steps decode
 * cooler, uncertain (high-entropy) steps decode hotter. On a completion
 * that mixes free-form reasoning with structured tool-call tokens this
 * is a per-token soft version of phase-aware sampling, with no phase
 * detection required.
 * - 0.0: Disabled (llama.cpp's default)
 * - 0.3–0.75: Exploratory range around a 0.6–1.0 base temperature
 *
 * Unset defers to llama.cpp's own default (0.0, disabled).
 *
 * Deliberately **not** part of the temperature-coupled trio, for the
 * reason DRY is not (#746): coupling would make a layer naming only a
 * `dynatemp_range` lose it to any lower layer naming a `temperature` —
 * the default state of every `reasoning`-tagged model — which costs the
 * most natural way of switching it on. Unlike the trio, its meaning is
 * anchored to whatever base temperature actually resolves, so an
 * orphaned range stays coherent.
 */
dynatempRange: number | null, 
/**
 * Dynamic-temperature exponent, shaping how sharply the effective
 * temperature responds to entropy. Inert while
 * [`dynatemp_range`](Self::dynatemp_range) is unset or zero.
 * Unset defers to llama.cpp's own default (1.0).
 */
dynatempExponent: number | null, 
/**
 * Top-n-sigma: keep only tokens whose *pre-softmax* logit is within
 * `n × σ` of the maximum (arXiv 2411.07641). Because it truncates the
 * unscaled logits, the candidate set does not widen as temperature
 * rises — the property that makes it a candidate for keeping tool-call
 * tokens stable while a reasoning model decodes hot.
 * - ≤ 0.0: Disabled (llama.cpp's default is −1.0)
 * - 1.0–2.0: The paper's evaluated range
 *
 * Unset defers to llama.cpp's own default (−1.0, disabled).
 */
topNSigma: number | null, 
/**
 * DRY (Don't Repeat Yourself) penalty strength.
 *
 * Penalises tokens that would extend a sequence already present in the
 * context, which catches the multi-token degenerate loops that
 * `repeat_penalty` — a flat per-token penalty — cannot see.
 * - 0.0: Disabled (llama.cpp's default, and the floor here)
 * - 0.8: A common starting point for long agentic sessions
 *
 * Left alone on agentic turns, deliberately. An earlier version forced
 * this to `0` whenever a request carried tools, reasoning that structured
 * output legitimately repeats tokens. Both halves were wrong: llama.cpp's
 * sequence breakers already default to `\n`, `:`, `"`, `*` — two of which
 * are pervasive in JSON — and agentic clients send `tools` on *every*
 * request, so the pin would have disabled DRY for whole sessions, which
 * is the workload it exists for.
 *
 * llama.cpp's fifth DRY parameter, `--dry-sequence-breaker`, is not
 * modelled: it is a list of strings, and every layer of this hierarchy —
 * merge, coupling, the CLI flags, the settings mirror — is built for
 * scalars. It is also the right lever if DRY is ever seen mangling a tool
 * call, so modelling it is the follow-up, not switching DRY off.
 */
dryMultiplier: number | null, 
/**
 * DRY penalty base, the exponent applied per token of matched sequence
 * length. Higher grows the penalty faster on longer repeats.
 * Unset defers to llama.cpp's own default (1.75).
 */
dryBase: number | null, 
/**
 * Sequence length, in tokens, that DRY tolerates before penalising.
 * Unset defers to llama.cpp's own default (2).
 */
dryAllowedLength: number | null, 
/**
 * How far back DRY scans for repeats, in tokens. `0` disables the
 * penalty; llama.cpp resolves negative values against the context size.
 * Unset defers to llama.cpp's own default (64).
 */
dryPenaltyLastN: number | null, 
/**
 * RNG seed for the sampler.
 *
 * Unset means llama.cpp draws a fresh random seed per request, which is
 * what it reports as `4294967295` (`u32::MAX`) in `/slots`.
 *
 * # Request-scoped by design, like `max_tokens`
 *
 * This is the second field in this struct that is **not a sampling
 * policy**. Every other one answers "how should this model sample?" and is
 * worth storing per model; a seed answers "make *this run* reproducible",
 * and a seed stored per model would pin every response that model ever
 * produces to the same text. So:
 *
 * - no floor names it, on either class floor;
 * - nothing gglib writes at import names it;
 * - the CLI, profile and settings surfaces do not expose it.
 *
 * It lives here anyway, rather than beside the hierarchy, for the reason
 * `max_tokens` does: this struct is the single thing that becomes the
 * request body ([`Self::to_openai_json_patch`]), and a value that reaches
 * the wire any other way is a value the ladder cannot explain and the
 * [readback] cannot check. llama.cpp reports the applied seed in
 * `/slots`, so routing it through here is what makes "did my seed actually
 * land?" an answerable question rather than an assumption — which is the
 * whole point of seeding a benchmark.
 *
 * [readback]: https://github.com/mmogr/gglib/blob/main/crates/gglib-proxy/src/sampling_audit.rs
 */
seed: number | null, 
/**
 * How hard the model is *asked* to think — a **prompt-shaping template
 * control**, not a sampler.
 *
 * Every other field in this struct configures llama.cpp's sampler chain.
 * This one does not touch it. It is parsed off the top-level `OpenAI`
 * body, stored as a Jinja kwarg and handed to the chat template, which
 * may render it into the prompt, may branch on it, or — on most models —
 * may never read the variable at all. It changes what the model is shown,
 * not how its logits are cut.
 *
 * # The wire, measured
 *
 * Against the pinned build ([ADR 0007] finding 7c):
 *
 * | sent | llama-server | why it matters here |
 * |---|---|---|
 * | `"high"` | 200, kwarg set | the ordinary case |
 * | `"banana"` | 200, **rendered into the prompt verbatim** | nothing upstream validates this field |
 * | `42` | 200, kwarg dropped, template default applies | a wrong type degrades silently |
 * | `""` | 200, ignored | already means "no opinion" |
 * | `"none"` | 200, kwarg **erased** | on `gpt-oss` the template's own `medium` fallback then fires |
 *
 * # An enum makes gglib stricter than upstream, deliberately
 *
 * [`extract_client_sampling`]'s doctrine is to "accept what upstream
 * accepts and reject what upstream rejects, so gglib never becomes the
 * stricter of the two". A closed [`ReasoningEffort`] plainly violates it:
 * llama-server takes `"banana"` and gglib will not.
 *
 * The doctrine's premise is that upstream is the authority on what a
 * field means, so disagreeing with it can only cost a value that would
 * have worked. That premise is false for exactly this field. ADR 0007
 * finding 7c measured the asymmetry: upstream **governs the budget** —
 * `reasoning_budget_tokens: -2` is a clean HTTP 400 naming the range —
 * and **does not govern effort at all**. There is no allowlist, no type
 * check, and no check that the loaded template reads the variable. Where
 * upstream has no opinion, gglib's governance is not the *stricter* of
 * two; it is the only one there is.
 *
 * And the failure mode is not a rejected-but-valid value. `"banana"` does
 * not fail, it renders: the user's own prompt gains a line reading
 * `Reasoning: banana`, and the model answers as if a person had typed it.
 * Passing that through is not accepting what upstream accepts, it is
 * forwarding a typo into a prompt. A rejected field costs the client its
 * `reasoning_effort` and is reported by name
 * ([`FieldIssue::Rejected`]); a forwarded typo costs the answer and is
 * reported nowhere.
 *
 * That trade only exists if the rejection also *removes the key*, and it
 * is this field that forces the point. Every other reader here rejects
 * only what upstream would have rejected too, so a forwarded reject came
 * back as an HTTP 400 and the damage was visible; and floored fields are
 * overwritten by the resolved patch anyway. This field is neither — no
 * layer or floor ever names it (`no_floor_names_a_reasoning_control`) and
 * upstream validates nothing — so a rejection that stopped at the layer
 * would be a report with no effect, and `"banana"` would reach the
 * prompt with gglib's own `client_fields_rejected` recording that it had
 * been stopped. See the body cleanup in `request_pipeline::sampling`, and
 * `a_rejected_effort_level_never_reaches_the_wire` for the pin.
 *
 * The narrower rule the doctrine actually encodes still holds and is
 * obeyed by this field's twin: see
 * [`reasoning_budget_tokens`](Self::reasoning_budget_tokens), which
 * accepts upstream's full `-1..=i32::MAX` and rejects precisely what
 * upstream 400s on.
 *
 * # Permanently Blind
 *
 * Neither this nor the budget appears in `/slots` or `/props`;
 * `task_params::to_json` exports no reasoning field in either branch. [ADR
 * 0004]'s readback can confirm a `top_k` arrived and can never confirm
 * this did. The provenance record is the whole account — which is why the
 * field is modelled here rather than left to ride the body ungoverned
 * (ADR 0007 finding 6, the #779 shape under a new name).
 *
 * # No floor names one
 *
 * See [`with_hardcoded_defaults`]. Several templates default themselves
 * (`gpt-oss` to `medium`); a floor here would override each template's own
 * choice with a value nobody made.
 *
 * [ADR 0004]: https://github.com/mmogr/gglib/blob/main/docs/adr/0004-observe-the-sampling-boundary.md
 * [ADR 0007]: https://github.com/mmogr/gglib/blob/main/docs/adr/0007-ask-the-server-for-template-capabilities.md
 * [`extract_client_sampling`]: Self::extract_client_sampling
 * [`with_hardcoded_defaults`]: Self::with_hardcoded_defaults
 */
reasoningEffort: ReasoningEffort | null, 
/**
 * How many tokens of thinking the model is allowed before it is cut off —
 * a **budget**, not a sampler and not a taste.
 *
 * It says what this request *is* (a turn that may spend at most `n`
 * tokens reasoning), the same category `max_tokens` occupies, and it is
 * enforced by llama.cpp itself (`common/reasoning-budget.{h,cpp}`) rather
 * than by a template that may or may not read a variable. That is what
 * puts it on the client-authoritative side of the trust gate while its
 * twin [`reasoning_effort`](Self::reasoning_effort) is gated — see
 * [`crate::request_pipeline::sampling`], which states the split where the
 * carve-out is coded.
 *
 * # The wire, measured — and the range is upstream's, not gglib's
 *
 * Range-validated on the pinned build: `-1 <= v <= 2147483647`, and `-2`
 * comes back as a clean HTTP 400 naming the range ([ADR 0007]
 * finding 7c). So the full `-1..=i32::MAX` is accepted here and only
 * values below `-1` are rejected — gglib matches upstream's own 400
 * exactly and adds nothing. This is the doctrine at
 * [`extract_client_sampling`] applied straight, and it is the reason the
 * departure argued on `reasoning_effort` is a departure about *that*
 * field rather than about reasoning controls in general.
 *
 * - `-1` — defer to the launch-time `--reasoning-budget` default.
 * - `0` — valid, and the honest spelling of "stop thinking immediately".
 *   It is what gglib offers instead of `reasoning_effort: "none"`, which
 *   yields *medium* thinking on `gpt-oss` (ADR 0007 decision 4).
 *
 * A value gglib refuses (below `-1`) is dropped from the layer and
 * **left in the forwarded body**, unlike its twin: upstream's own 400
 * names this field and its range, which is a better answer to the client
 * than a silent substitution and keeps gglib no stricter than upstream.
 * See [`FieldIssue::Rejected`].
 *
 * # The alias
 *
 * Upstream also accepts `thinking_budget_tokens`
 * ([`THINKING_BUDGET_TOKENS_KEY`]) as a second spelling of this
 * parameter. gglib reads it — a name it did not read was a name the trust
 * gate could not govern — and emits the canonical one only, erasing the
 * alias from every forwarded body so the two spellings cannot disagree
 * about the resolved value. With both sent, the canonical key wins. See
 * [`read_reasoning_budget_tokens`].
 *
 * # Permanently Blind, like its twin
 *
 * It is parsed into `params.sampling`, but `task_params::to_json`
 * serialises no `reasoning_budget_*` field, so nothing echoes it in
 * `/slots` or `/props` either. ADR 0007's finding 7a is a correction to
 * that ADR's own earlier claim; do not re-derive an echo from the request
 * *parse* table.
 *
 * # No floor names one
 *
 * See [`with_hardcoded_defaults`]. A fleet-wide thinking budget is a
 * tuning decision with measurement behind it, and `-1` — the "defer"
 * sentinel — is exactly what omitting the key already means.
 *
 * [ADR 0007]: https://github.com/mmogr/gglib/blob/main/docs/adr/0007-ask-the-server-for-template-capabilities.md
 * [`extract_client_sampling`]: Self::extract_client_sampling
 * [`with_hardcoded_defaults`]: Self::with_hardcoded_defaults
 */
reasoningBudgetTokens: number | null, };
