// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpEnvEntryDto } from "./McpEnvEntryDto";
import type { McpLifecycle } from "./McpLifecycle";
import type { McpServerConfigDto } from "./McpServerConfigDto";

/**
 * MCP server DTO for serialization.
 */
export type McpServerDto = { id: number, name: string, server_type: string, config: McpServerConfigDto, enabled: boolean, lifecycle: McpLifecycle, env: Array<McpEnvEntryDto>, created_at: string, last_connected_at?: string, 
/**
 * Whether the server configuration is valid
 */
is_valid: boolean, 
/**
 * Last validation or runtime error
 */
last_error?: string, };
