// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to call an MCP tool.
 */
export type McpToolCallRequest = { tool_name: string, 
/**
 * Tool arguments, shaped by the tool's own schema and opaque here.
 */
arguments: Record<string, unknown>, };
