// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultsOrigin } from "./DefaultsOrigin";
import type { InferenceConfig } from "./InferenceConfig";
import type { Support } from "./Support";

/**
 * Complete model details for the inspect view.
 *
 * Carries the domain [`Model`] in full — raw GGUF metadata, MoE topology and
 * HuggingFace provenance, none of which the list endpoint sends. It is the
 * single shared contract consumed by:
 *
 * - CLI: `gglib model inspect` (human-readable or `--json`)
 * - Axum: `GET /api/models/:id/detail`
 * - GUI frontend: model detail panel
 *
 * # Not a superset of [`GuiModel`]
 *
 * It was described as one for a long time, and a TypeScript mirror was
 * written to match by extending the list row — which advertised
 * `server_defaults` and `benchmark_summary` on a response that has never
 * carried either. The two shapes overlap; neither contains the other.
 */
export type ModelDetailDto = { 
/**
 * Database ID of the model.
 */
id: number, 
/**
 * Human-readable name.
 */
name: string, 
/**
 * Absolute path to the GGUF file on disk.
 */
filePath: string, 
/**
 * Parameter count in billions.
 */
paramCountB: number, 
/**
 * Model architecture (e.g. `"llama"`, `"mistral"`).
 */
architecture?: string, 
/**
 * Quantization type (e.g. `"Q4_K_M"`, `"F16"`).
 */
quantization?: string, 
/**
 * Maximum context length in tokens.
 */
contextLength?: number, 
/**
 * Total number of experts (MoE models only).
 */
expertCount?: number, 
/**
 * Experts activated per token (MoE models only).
 */
expertUsedCount?: number, 
/**
 * Shared experts that are always active (MoE models only).
 */
expertSharedCount?: number, 
/**
 * HuggingFace repository ID (e.g. `"bartowski/Llama-3.1-8B-GGUF"`).
 */
hfRepoId?: string, 
/**
 * Original filename on HuggingFace Hub.
 */
hfFilename?: string, 
/**
 * Git commit SHA from HuggingFace Hub.
 */
hfCommitSha?: string, 
/**
 * When the model was downloaded from HuggingFace (`"%Y-%m-%d %H:%M:%S"`).
 */
downloadDate?: string, 
/**
 * Last time an update check was performed (`"%Y-%m-%d %H:%M:%S"`).
 */
lastUpdateCheck?: string, 
/**
 * User-defined and auto-generated tags.
 */
tags: Array<string>, 
/**
 * Capability flags serialized as a `u32` bit-field.
 *
 * A `bitflags` newtype, so it crosses the wire as a bare number and
 * cannot derive `TS` itself — see [`GuiModel::capabilities`].
 */
capabilities: number, 
/**
 * Per-model inference parameter overrides.
 */
inferenceDefaults?: InferenceConfig, 
/**
 * Whether [`Self::inference_defaults`] was set by the user or
 * auto-detected at import time. See `gglib_core::domain::DefaultsOrigin`.
 */
defaultsOrigin?: DefaultsOrigin, 
/**
 * Whether this model's chat template reads `reasoning_effort`, as
 * llama-server reported it the last time the model was served.
 *
 * # Three states, and the third is the common one
 *
 * Carried as [`Support`] rather than a `bool` or an `Option<bool>`,
 * because a client has to be able to tell *not supported* from *nobody has
 * looked*. Most rows are the latter: the caps are read from `GET /props`
 * while the model is running, so every model that has never been launched
 * on this installation answers `unknown` and keeps answering it until it
 * is.
 *
 * A `bool` would collapse `unknown` into `false`, and a client would then
 * grey out the reasoning control on every unlaunched model — the
 * unknown-gates mistake ADR 0007 decision 3 forbids the server to make,
 * reproduced one layer out. The server's own suppression acts only on
 * [`Support::No`]; a surface should offer the control on `yes` and
 * `unknown` alike, and explain itself on `no`.
 *
 * # Why the one field and not the whole caps object
 *
 * `TemplateCaps` carries nine bools. Eight describe things gglib already
 * models in [`Self::capabilities`] from its own catalog — tools, system
 * role, parallel calls — and publishing a second, differently-sourced
 * answer to the same question invites a client to read whichever it finds
 * first. The ninth has no other home, and this is it. A surface that
 * genuinely needs the raw self-report should get its own endpoint rather
 * than a `serde` alias on this one.
 *
 * [`Support`]: gglib_core::domain::Support
 * [`Support::No`]: gglib_core::domain::Support::No
 */
reasoningEffortSupport: Support, 
/**
 * When the model was first added to the database (`"%Y-%m-%d %H:%M:%S"`).
 */
addedAt: string, 
/**
 * Whether the model is currently being served.
 */
isServing: boolean, 
/**
 * Port the model is served on, if currently serving.
 */
port?: number, 
/**
 * All raw key-value pairs stored from the GGUF file.
 *
 * Presentation layers decide whether to surface this.  The CLI gates it
 * behind `--metadata`; the GUI may show it in a collapsible panel.
 */
metadata: { [key in string]: string }, };
