// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire form of [`ParamSource`], with the ladder index resolved to a name.
 */
export type ProvenanceKindDto = "layer" | "floor" | "floorCoupled" | "unset" | "suppressedByTemplate";
