// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The verdict arm of [`PublishedDefaultDto`].
 */
export type PublishedStateDto = { "state": "deferred", 
/**
 * What the model author published, and what the sampler will use.
 */
published: number, } | { "state": "restated", 
/**
 * The value both sides name.
 */
published: number, } | { "state": "overridden", 
/**
 * What the model author published.
 */
published: number, 
/**
 * What gglib puts on the wire instead.
 */
sending: number, } | { "state": "unreadable" };
