// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reasoning-effort level gglib is willing to put on the wire.
 *
 * # This enum is where gglib is deliberately stricter than upstream
 *
 * [`InferenceConfig::extract_client_sampling`]'s coercion doctrine is "accept
 * what upstream accepts and reject what upstream rejects, so gglib never
 * becomes the stricter of the two". A closed enum breaks that rule for this
 * one field, on purpose, and the exception is argued rather than assumed —
 * see [`InferenceConfig::reasoning_effort`], which carries the argument.
 *
 * # The levels
 *
 * The six are llama-server's own documented set, taken from its
 * `--reasoning-effort` help text on the pinned build. They are *offered*
 * levels, not honoured ones: a template that never branches on the variable
 * ignores every one of them, and even a template that reads it may only act
 * on some (upstream's own tests show DeepSeek-V4 rendering something special
 * for `"max"` and nothing at all for `"high"` or `"low"` — ADR 0007
 * finding 3).
 *
 * # `"none"` is not here, and its absence is the decision
 *
 * llama-server accepts `reasoning_effort: "none"` and treats it specially: it
 * **erases** the kwarg rather than passing it through. On `gpt-oss` the
 * template's own `{%- set reasoning_effort = "medium" %}` fallback then
 * fills the hole, so `"none"` yields **medium** thinking — confirmed live
 * against the pinned binary, not inferred. Offering it as a level would ship
 * a control whose most obvious value does the opposite of what it reads as.
 * "Stop thinking" is
 * [`reasoning_budget_tokens: 0`](super::InferenceConfig#structfield.reasoning_budget_tokens),
 * which is sampler-enforced and range-validated upstream. See ADR 0007
 * finding 4 and decision 4.
 *
 * [ADR 0007]: https://github.com/mmogr/gglib/blob/main/docs/adr/0007-ask-the-server-for-template-capabilities.md
 * [`InferenceConfig::extract_client_sampling`]: super::InferenceConfig::extract_client_sampling
 * [`InferenceConfig::reasoning_effort`]: super::InferenceConfig#structfield.reasoning_effort
 * [`InferenceConfig::reasoning_budget_tokens`]: super::InferenceConfig#structfield.reasoning_budget_tokens
 */
export type ReasoningEffort = "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
