// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultsOrigin } from "./DefaultsOrigin";
import type { InferenceConfig } from "./InferenceConfig";
import type { ParamProvenanceDto } from "./ParamProvenanceDto";
import type { PublishedDefaultDto } from "./PublishedDefaultDto";
import type { SuppressedEffortDto } from "./SuppressedEffortDto";

/**
 * A model's resolved sampling parameters and where each value came from.
 *
 * Consumers:
 * - Axum: `GET /api/models/:id/explain`
 * - GUI frontend: the inspector's Sampling section
 */
export type SamplingExplanationDto = { 
/**
 * The fully resolved configuration, after floors.
 *
 * Carried whole rather than copied field-by-field into
 * [`ParamProvenanceDto`], so each value keeps the width it was declared
 * at and `serde_json` emits the shortest representation that round-trips
 * — `0.95`, not the `0.949999988079071` a detour through `f64` produces.
 */
resolved: InferenceConfig, 
/**
 * Per-parameter provenance, in [`FieldSources::iter`](gglib_core::domain::FieldSources::iter)'s display order.
 */
sources: Array<ParamProvenanceDto>, 
/**
 * The profile applied, if the caller named one.
 */
profile: string | null, 
/**
 * Whether the model carries the `reasoning` tag, which selects the floor.
 */
isReasoning: boolean, 
/**
 * Whether client-supplied sampling is trusted, which the table cannot
 * show: that rung is never stored on the model.
 */
trustClientSampling: boolean, 
/**
 * What this model's own GGUF publishes, for the fields where it publishes
 * anything at all.
 *
 * Empty on almost every model, and empty is the *interesting* default:
 * carrying a `notPublished` entry per field would put five noise rows on
 * every ordinary model to say nothing. A parameter absent from this list
 * has no author recommendation to honour or displace.
 *
 * The provenance column alone cannot answer this. Since llama.cpp PR
 * #17120 a `general.sampling.*` key is the server's default for every
 * field gglib does not name, so `unset` means *the model's own number
 * applies* on a model that published one, and *the build's default
 * applies* on a model that did not — and those render identically without
 * this.
 */
published: Array<PublishedDefaultDto>, 
/**
 * Where the model's stored defaults came from.
 *
 * `Published` and `AutoDetected` share a ladder rung — both are
 * unreviewed, so both rank below global settings — which means
 * [`ParamProvenanceDto::layer`] alone cannot name its own source. Without
 * this, a recipe fetched from the model author renders as gglib's
 * reasoning-tag guess.
 *
 * The domain enum itself, not a re-spelling of it: the library list
 * reports this same column, and a wire form that differed from it in
 * casing alone meant one stored value reached a client under two names.
 */
defaultsOrigin: DefaultsOrigin | null, 
/**
 * The `reasoning_effort` this model's template would ignore, when the
 * stored configuration resolves one it does not read.
 *
 * # Why a table row is not enough
 *
 * The suppression *is* in [`Self::sources`] — that entry reads
 * [`SuppressedByTemplate`](ProvenanceKindDto::SuppressedByTemplate) — and
 * [`Self::resolved`] carries `null`, because that is what would be sent.
 * Between them a client can say *something was suppressed* and nothing
 * more: the level is gone from `resolved`, and the rung that asked for it
 * has been overwritten by the marker. Those two are the whole content of
 * the sentence a reader needs — "the `:high` profile asks for `high`; this
 * model's template does not read `reasoning_effort`" — so they are carried
 * here or they are carried nowhere.
 *
 * # It describes a request that has not happened
 *
 * This endpoint explains *stored configuration*. Nothing has been sent, so
 * this is a conditional: on any request against this model, that is what
 * would happen. A surface must word it that way. The unconditional twin
 * lives on the proxy's sampling audit, where a request really did run.
 */
effortSuppressed?: SuppressedEffortDto, };
