// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The wire form of [`SamplingLayer`].
 */
export type SamplingLayerDto = "request" | "profile" | "modelUserSet" | "global" | "modelAutoDetected";
