// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceConfig } from "./InferenceConfig";

/**
 * Request body for starting a server.
 */
export type StartServerRequest = { contextLength: number | null, port: number | null, jinja: boolean | null, reasoningFormat: string | null, 
/**
 * Number of MTP draft tokens (`--spec-draft-n-max`).
 *
 * `None` = auto-detect from model tags.  `Some(0)` = explicitly disabled.
 * `Some(n > 0)` = explicitly enable with n tokens.
 */
mtpDraftNMax: number | null, 
/**
 * Minimum acceptance probability for MTP draft tokens (`--spec-draft-p-min`).
 *
 * Only meaningful when `mtp_draft_n_max` is `Some`.  Defaults to `0.75`.
 */
mtpDraftPMin: number | null, 
/**
 * Inference parameters for this serve session (overrides model/global defaults).
 */
inferenceParams: InferenceConfig | null, 
/**
 * Memory-lock the model into RAM (`--mlock`).
 */
mlock: boolean, };
