// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for starting a server.
 */
export type StartServerResponse = { port: number, message: string, };
