// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { SamplingLayerDto } from "./SamplingLayerDto";

/**
 * A resolved `reasoning_effort` this model's template would not read.
 */
export type SuppressedEffortDto = { 
/**
 * The level the ladder resolved.
 */
level: ReasoningEffort, 
/**
 * The rung that supplied it, before the suppression overwrote the entry
 * in [`SamplingExplanationDto::sources`].
 *
 * `None` only for a ladder index this module cannot name, which the five
 * rungs it resolves cannot produce — and never for a floor, because no
 * floor names an effort.
 */
layer?: SamplingLayerDto, };
