// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for tool/function calling support detection.
 *
 * Used for both HuggingFace model metadata and local running server queries.
 */
export type ToolSupportResponse = { supports_tool_calls: boolean, confidence: number, detected_format: string | null, };
