// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpEnvEntryDto } from "./McpEnvEntryDto";
import type { McpLifecycle } from "./McpLifecycle";

/**
 * Request to update an MCP server.
 */
export type UpdateMcpServerRequest = { name: string | null, command: string | null, args: Array<string> | null, working_dir: string | null, path_extra: string | null, url: string | null, env: Array<McpEnvEntryDto> | null, enabled: boolean | null, lifecycle: McpLifecycle | null, };
