// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of applying an upgrade.
 */
export type UpgradeOutcome = { 
/**
 * False when the model was already at the latest revision.
 */
updated: boolean, latestSha: string, 
/**
 * The new on-disk path, present only when an upgrade ran.
 */
filePath: string | null, };
