// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a newer HuggingFace revision exists for a model.
 *
 * `currentSha` is `None` when the model was imported without a recorded
 * revision. The check treats that as "an update exists" (there is no
 * baseline to compare against), so callers should present a missing
 * baseline distinctly rather than as a genuine new revision.
 */
export type UpgradeCheck = { hasUpdate: boolean, currentSha: string | null, latestSha: string, };
