// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedModelSnapshot } from "./QueuedModelSnapshot";
import type { ResidentSlotSnapshot } from "./ResidentSlotSnapshot";
import type { SecondarySlotStatus } from "./SecondarySlotStatus";

/**
 * Everything the admission queue and resident set look like right now.
 */
export type AdmissionSnapshot = { 
/**
 * Models resident in VRAM, primary first. Empty before anything has been
 * launched.
 */
slots: Array<ResidentSlotSnapshot>, 
/**
 * Models with requests waiting, oldest waiter first. Empty in the steady
 * state — a non-empty list means traffic is being batched behind a swap.
 */
queued: Array<QueuedModelSnapshot>, 
/**
 * Requests that have waited in the queue since the runtime started.
 * Compare against [`Self::total_swaps`]: a large ratio is the queue doing
 * its job, batching many requests behind one swap.
 */
total_queued: number, 
/**
 * Model swaps performed since the runtime started.
 */
total_swaps: number, 
/**
 * Why the second slot is or is not in use.
 */
secondary_slot: SecondarySlotStatus, };
