// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskCategory } from "./TaskCategory";
import type { TuneTaskResult } from "./TuneTaskResult";

/**
 * One task's outcome under both arms, for drill-down.
 *
 * Both sides carry **one entry per seed**, in seed order, rather than a single
 * result. Collapsing them to a representative run would hide the thing a
 * multi-seed eval is for: a task that passes 3/3 under one arm and 1/3 under
 * the other is a different finding from one that passes 3/3 versus 0/3, and
 * both render as "passed / failed" once the per-seed detail is gone.
 */
export type AgenticTaskComparison = { 
/**
 * Task identifier from the suite.
 */
task_id: string, 
/**
 * The task's BFCL-style category.
 */
category: TaskCategory, 
/**
 * Per-seed results under the raw arm, in seed order.
 */
raw: Array<TuneTaskResult>, 
/**
 * Per-seed results under the gglib arm, in seed order.
 */
gglib: Array<TuneTaskResult>, };
