// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * Content carried by an [`AgentMessage::Assistant`] turn.
 *
 * A flat struct with optional `text` and a (possibly empty) `tool_calls` vec.
 * At the wire level, at least one of the two fields must be present — the
 * hand-rolled [`Deserialize`] impl (in [`super::messages_serde`]) enforces
 * this.
 *
 * # Serde
 *
 * Serializes/deserializes as a flat map so it can be `#[serde(flatten)]`-ed
 * directly into the parent [`AgentMessage`] object:
 *
 * | State | JSON fields |
 * |-------|-------------|
 * | text only | `"content": "..."` |
 * | tool calls only | `"tool_calls": [...]` |
 * | both | `"content": "...", "tool_calls": [...]` |
 *
 * Custom `Serialize` and `Deserialize` impls are in
 * [`super::messages_serde`].
 */
export type AssistantContent = { 
/**
 * Optional text content from the model.  `None` when the model produced
 * only tool calls with no text preamble.
 *
 * Both annotations below restate what [`super::messages_serde`]'s
 * hand-written impls do, because ts-rs reads *fields* and cannot see a
 * manual `Serialize`. Without them the binding claims a `text` key that
 * no payload has ever carried. The table above is the contract.
 */
content?: string, 
/**
 * Tool calls requested by the model.  Empty when the model produced a
 * text-only response (final answer).
 *
 * `as Option<…>` because the impl omits the key entirely for an empty
 * vec, which is a state a bare `Vec` cannot express in TypeScript.
 */
tool_calls?: Array<ToolCall>, };
