// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttemptCounts } from "./AttemptCounts";
import type { CompletionKey } from "./CompletionKey";
import type { CompletionKind } from "./CompletionKind";
import type { DownloadId } from "./DownloadId";

/**
 * Details for a single completed artifact in a queue run.
 */
export type CompletionDetail = { 
/**
 * Stable artifact identity key.
 */
key: CompletionKey, 
/**
 * Human-readable display name for UI.
 */
display_name: string, 
/**
 * Most recent result for this artifact.
 */
last_result: CompletionKind, 
/**
 * Unix timestamp (milliseconds since epoch) of last completion.
 */
last_completed_at_ms: number, 
/**
 * All download IDs that contributed to this completion.
 * Multiple IDs indicate retries or re-queues.
 */
download_ids: Array<DownloadId>, 
/**
 * Breakdown of attempts by result kind.
 */
attempt_counts: AttemptCounts, };
