// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";
import type { DownloadSummary } from "./DownloadSummary";
import type { QueueRunSummary } from "./QueueRunSummary";

/**
 * Single discriminated union for all download events.
 *
 * The frontend handles this as a TypeScript discriminated union:
 *
 * ```typescript
 * type DownloadEvent =
 *   | { type: "queue_snapshot"; items: DownloadSummary[]; max_size: number }
 *   | { type: "download_started"; id: string; shard_index?: number; total_shards?: number }
 *   | { type: "download_progress"; id: string; downloaded: number; total: number;
 *       speed_bps?: number; eta_seconds?: number; percentage: number }
 *   | { type: "shard_progress"; id: string; shard_index: number;
 *       speed_bps?: number; eta_seconds?: number; ... }
 *   | { type: "download_completed"; id: string }
 *   | { type: "download_failed"; id: string; error: string }
 *   | { type: "download_cancelled"; id: string }
 *   | { type: "download_notice"; id: string; message: string };
 * ```
 *
 * `speed_bps` and `eta_seconds` are **optional and omitted when unknown** — a
 * download that has just started has no meaningful rate yet. Renderers must
 * show a placeholder for the absent case rather than substituting `0`, and
 * must never compute a rate of their own from successive `downloaded` values;
 * the manager's `RateEstimator` is the only source. TypeScript reads this
 * type through its generated binding; there is no mirror to keep in step.
 */
export type DownloadEvent = { "type": "queue_snapshot", 
/**
 * All items currently in the queue.
 */
items: Array<DownloadSummary>, 
/**
 * Maximum queue capacity.
 */
max_size: number, } | { "type": "download_started", 
/**
 * Canonical ID of the download.
 */
id: string, 
/**
 * Current shard index (0-based), present only for sharded downloads.
 */
shard_index?: number, 
/**
 * Total number of shards, present only for sharded downloads.
 */
total_shards?: number, } | { "type": "download_progress", 
/**
 * Canonical ID of the download.
 */
id: string, 
/**
 * Bytes downloaded so far.
 */
downloaded: number, 
/**
 * Total bytes to download.
 */
total: number, 
/**
 * Current download speed in bytes per second.
 *
 * Absent until the estimator has warmed up. This is deliberately not
 * `0.0`: zero is a real reading meaning "stalled", and conflating the
 * two is what rendered `ETA: 0s` on a healthy download.
 */
speed_bps?: number, 
/**
 * Estimated time remaining in seconds; absent when not yet known.
 */
eta_seconds?: number, 
/**
 * Progress percentage (0.0 - 100.0).
 */
percentage: number, } | { "type": "shard_progress", 
/**
 * Canonical ID of the download (group ID).
 */
id: string, 
/**
 * Current shard index (0-based).
 */
shard_index: number, 
/**
 * Total number of shards.
 */
total_shards: number, 
/**
 * Filename of the current shard.
 */
shard_filename: string, 
/**
 * Bytes downloaded for current shard.
 */
shard_downloaded: number, 
/**
 * Total bytes for current shard.
 */
shard_total: number, 
/**
 * Aggregate bytes downloaded across all shards.
 */
aggregate_downloaded: number, 
/**
 * Aggregate total bytes across all shards.
 */
aggregate_total: number, 
/**
 * Current download speed in bytes per second; absent until known.
 *
 * Measured across the whole shard group, not reset per shard.
 */
speed_bps?: number, 
/**
 * Estimated time remaining in seconds; absent when not yet known.
 */
eta_seconds?: number, 
/**
 * Aggregate progress percentage (0.0 - 100.0).
 */
percentage: number, } | { "type": "download_completed", 
/**
 * Canonical ID of the download.
 */
id: string, 
/**
 * Optional success message.
 */
message?: string, } | { "type": "download_failed", 
/**
 * Canonical ID of the download.
 */
id: string, 
/**
 * Error message describing what went wrong.
 */
error: string, } | { "type": "download_cancelled", 
/**
 * Canonical ID of the download.
 */
id: string, } | { "type": "download_status_changed", 
/**
 * Canonical ID of the download.
 */
id: string, 
/**
 * New status of the download.
 */
status: DownloadStatus, } | { "type": "download_notice", 
/**
 * Canonical ID of the download.
 */
id: string, 
/**
 * Human-readable note to display in place of progress.
 */
message: string, } | { "type": "queue_run_complete", 
/**
 * Complete summary of the queue run.
 */
summary: QueueRunSummary, };
