// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of running `llama-bench` on a single model.
 */
export type ModelPerfResult = { 
/**
 * Database ID of this result row (set after persistence).
 */
id: number | null, 
/**
 * Foreign key → `models.id`.
 */
model_id: number, 
/**
 * Foreign key → `benchmark_runs.id` (nullable; SET NULL on run delete).
 */
run_id: number | null, 
/**
 * Prompt-processing throughput (tokens/sec).
 */
pp_tps: number, 
/**
 * Token-generation throughput (tokens/sec).
 */
tg_tps: number, 
/**
 * Number of prompt tokens used in the benchmark.
 */
pp_tokens: number, 
/**
 * Number of generation tokens used in the benchmark.
 */
tg_tokens: number, 
/**
 * Backend reported by llama-bench (e.g. "Metal", "CUDA", "CPU").
 */
backend: string | null, 
/**
 * Number of GPU layers offloaded.
 */
ngl: number | null, 
/**
 * Context size used.
 */
context_size: number | null, 
/**
 * Number of repetitions averaged.
 */
repetitions: number, 
/**
 * UTC timestamp of this result.
 */
created_at: string, };
