// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeValues } from "./RangeValues";

/**
 * Filter options for the model library UI.
 *
 * Contains aggregate data about available models for building
 * dynamic filter controls.
 */
export type ModelFilterOptions = { 
/**
 * All distinct quantization types present in the library.
 */
quantizations: Array<string>, 
/**
 * Minimum and maximum parameter counts (in billions).
 */
param_range: RangeValues | null, 
/**
 * Minimum and maximum context lengths.
 */
context_range: RangeValues | null, 
/**
 * Minimum and maximum `latest_tg_tps` from benchmark summaries.
 * `None` when no models have been benchmarked.
 */
speed_range: RangeValues | null, };
