// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overall health status for a model.
 */
export type OverallHealth = "healthy" | "unhealthy" | "unverifiable";
