// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The paired view of the raw-versus-gglib comparison.
 *
 * The two real arms run the **same seeds on the same tasks**, so every
 * `(task, seed)` cell is a matched pair — and pairing is what removes the
 * eval's identical-arm spread from the comparison. The ceiling experiment
 * (tune runs #12–#32, ADR 0004's postscript) resolved a +0.067 effect
 * through noise wider than that *only* because it paired per run; the same
 * data has been sitting in [`AgenticEvalReport::tasks`] all along, compared
 * only as arm means.
 *
 * Pairs are on [`TuneTaskResult::tool_match_score`] — the one graded
 * per-run quality scalar. Pass/fail flips remain visible per task in
 * [`AgenticTaskComparison::pass_counts`]; folding them in here would double
 * count, since the match score is most of what decides `passed`.
 */
export type PairedEffect = { 
/**
 * Matched `(task, seed)` pairs in which both arms produced a real
 * observation.
 */
pairs: number, 
/**
 * Pairs both arms ran but at least one side never reached the model —
 * dropped from every number here, and reported so the drop is visible.
 */
unmeasured_pairs: number, 
/**
 * Pairs the gglib arm scored strictly higher.
 */
wins: number, 
/**
 * Pairs the raw arm scored strictly higher.
 */
losses: number, 
/**
 * Pairs with identical scores. On a suite where most tasks pass cleanly
 * under both arms this is the largest bucket, and that is information:
 * the arms mostly agree.
 */
ties: number, 
/**
 * Mean of `gglib − raw` over the measured pairs.
 */
mean_delta: number, 
/**
 * One-sided Wilcoxon signed-rank *p* for "gglib scores higher", by
 * normal approximation with tie correction.
 *
 * `None` below [`WILCOXON_MIN_PAIRS`] non-tied pairs — the approximation
 * is not trustworthy there, and rendering a statistic the design cannot
 * support is worse than rendering none (the [`EffectVerdict`] rule). At
 * small counts, read [`Self::wins`] against [`Self::losses`] instead.
 */
p_value: number | null, };
