// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health status of an individual shard after verification.
 */
export type ShardHealth = { "type": "healthy" } | { "type": "corrupt", 
/**
 * Expected SHA256 hash (from `HuggingFace` OID).
 */
expected: string, 
/**
 * Actual computed SHA256 hash.
 */
actual: string, } | { "type": "missing" } | { "type": "no_oid" };
