// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a shard within a sharded model download.
 *
 * [`preceding_bytes`](Self::preceding_bytes) and
 * [`group_total_bytes`](Self::group_total_bytes) carry the exact byte offsets
 * of this shard within the whole model, so aggregate progress does not have to
 * assume every shard is the same size. GGUF shard sets almost always end with
 * a smaller final shard, and estimating the group total as
 * `this_shard_size * shard_count` made the percentage both wrong and
 * discontinuous at every shard boundary.
 */
export type ShardInfo = { 
/**
 * 0-based index of this shard.
 */
shard_index: number, 
/**
 * Total number of shards in this model.
 */
total_shards: number, 
/**
 * The specific filename for this shard.
 */
filename: string, 
/**
 * Size of this shard file in bytes (if known).
 */
file_size?: number, 
/**
 * Summed size of every shard before this one (if all sizes are known).
 */
preceding_bytes?: number, 
/**
 * Summed size of every shard in the group (if all sizes are known).
 */
group_total_bytes?: number, };
