// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the audit has actually been able to observe.
 *
 * Deliberately not a bare count — see the module docs on `Blind`.
 */
export type AuditState = { "state": "not_yet_observed" } | { "state": "blind", 
/**
 * Human-readable cause: slots disabled, no `params` on this build,
 * upstream unreachable.
 */
reason: string, } | { "state": "comparing", 
/**
 * Requests *observed in flight* — never requests sent. See the
 * module docs: this instrument samples.
 */
comparisons: number, 
/**
 * How many of those disagreed on at least one field.
 */
divergences: number, };
