// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaselineReport } from "./BaselineReport";

/**
 * What the `/props` baseline read has produced for the running model.
 *
 * A tagged union rather than `Option<BaselineReport>`, for
 * [`AuditState`](crate::sampling_audit::AuditState)'s reason. "Nobody has
 * read it yet" and "the read was attempted and failed, and here is why" are
 * different facts, and an `Option` flattens both into the same `None` — after
 * which the only thing a surface can say is "not read yet", which is a claim
 * about a read that did happen.
 *
 * That is the blind-rendered-as-health collapse this subsystem exists to
 * prevent, one level down from where it was being prevented: the slot half
 * carried `Blind { reason }` from the start, and the baseline half did not.
 */
export type BaselineState = { "state": "not_yet_read" } | { "state": "unreadable", 
/**
 * Cause, in words a dashboard can show.
 */
reason: string, } | { "state": "read", 
/**
 * Per-field verdicts.
 */
report: BaselineReport, };
