// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaselineVerdict } from "./BaselineVerdict";

/**
 * One field of [`check_baseline`]'s answer.
 */
export type BaselineField = { 
/**
 * Wire name of the parameter.
 */
field: string, 
/**
 * What was concluded about it.
 */
verdict: BaselineVerdict, };
