// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the table a reading actually covered.
 *
 * A tagged union rather than the `conclusive: bool` it replaced, and the bool
 * is worth describing because of how it failed. It was computed as *"any
 * field reached a verdict"*, so a report in which two of seven fields were
 * checked and five could not be reported itself as conclusive — and the
 * dashboard's only conclusive-and-undrifted rendering is the sentence "All 7
 * sampler defaults match the values this build was measured at."
 *
 * That is [`AuditState`](crate::sampling_audit::AuditState)'s failure one
 * level up: not a field rendered as agreeing when it was unknown, but a
 * *report* rendered as complete when it was partial. The same rule applies
 * and the same remedy — make the state carry what it knows instead of
 * collapsing it to a yes/no.
 *
 * Orthogonal to whether anything drifted. [`Complete`](Self::Complete) says
 * every field was compared, not that every field agreed, so surfaces check
 * [`BaselineReport::drifted`] first and coverage second.
 */
export type BaselineCoverage = { "coverage": "complete" } | { "coverage": "partial", 
/**
 * Fields compared against the recorded table.
 */
checked: number, 
/**
 * Fields whose value came from the model's own GGUF, so the build's
 * default is unobservable for them on this launch.
 */
model_supplied: number, 
/**
 * Fields nothing could be concluded about.
 */
indeterminate: number, } | { "coverage": "blind", 
/**
 * Fields whose value came from the model's own GGUF.
 */
model_supplied: number, 
/**
 * Fields nothing could be concluded about.
 */
indeterminate: number, };
