// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `reasoning_budget_tokens` the most recent request resolved, and its rung.
 */
export type BudgetRung = { 
/**
 * The cap, in tokens. `0` is the documented "stop thinking".
 */
tokens: number, 
/**
 * The rung that supplied it.
 */
source: string, };
