// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point-in-time view of prompt-cache reuse since the proxy started.
 */
export type CacheUsage = { 
/**
 * Completed requests whose upstream reported a cached-token count.
 * The denominator for [`Self::cached_tokens`] and [`Self::prompt_tokens`].
 */
reporting_requests: number, 
/**
 * Completed requests whose upstream omitted the field. Excluded from
 * every other figure here — counted so a consumer can tell "no reuse"
 * apart from "no data".
 */
unreported_requests: number, 
/**
 * Total prompt tokens across [`Self::reporting_requests`].
 */
prompt_tokens: number, 
/**
 * Total prompt tokens served from the KV cache across those requests.
 * Always `<= prompt_tokens`.
 */
cached_tokens: number, 
/**
 * Prompt tokens in the most recent reporting request.
 */
last_prompt_tokens: number | null, 
/**
 * Tokens reused from cache in the most recent reporting request.
 */
last_cached_tokens: number | null, };
