// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveConnectionSnapshot } from "./ActiveConnectionSnapshot";
import type { AdmissionSnapshot } from "./AdmissionSnapshot";
import type { CacheStatus } from "./CacheStatus";
import type { CacheUsage } from "./CacheUsage";
import type { ContextSnapshot } from "./ContextSnapshot";
import type { LaunchNarration } from "./LaunchNarration";
import type { ModelDefectCounts } from "./ModelDefectCounts";
import type { SamplingAuditSnapshot } from "./SamplingAuditSnapshot";
import type { SlotSnapshot } from "./SlotSnapshot";
import type { UpstreamHealthSnapshot } from "./UpstreamHealthSnapshot";

/**
 * The single, unified proxy dashboard data contract.
 *
 * This is both the `GET /v1/proxy/status` response body and the event type
 * pushed over `GET /v1/proxy/status/stream`.
 */
export type DashboardSnapshot = { 
/**
 * Every currently in-flight model request — direct `/v1/chat/completions`
 * completions and `/v1/embeddings`.
 */
active_connections: Array<ActiveConnectionSnapshot>, 
/**
 * `true` if the running llama-server's `/slots` endpoint is reachable
 * and enabled. `false` if it's disabled (`--no-slots`) or currently
 * unreachable — see [`Self::slots_status`] for the reason in that case.
 */
slots_available: boolean, 
/**
 * Per-slot context usage, populated when [`Self::slots_available`] is
 * `true`. Empty otherwise.
 */
slots: Array<SlotSnapshot>, 
/**
 * Human-readable reason `slots` is empty. `None` when slots are
 * available; otherwise either the disabled notice or the poller's
 * last connect/timeout/parse error message.
 */
slots_status: string | null, 
/**
 * Most recent request snapshots, oldest first, capped at
 * [`RECENT_REQUEST_LIMIT`].
 */
recent_requests: Array<ContextSnapshot>, 
/**
 * Total requests handled since the proxy started, including any
 * evicted from `recent_requests`'s ring buffer.
 */
total_requests: number, 
/**
 * Total requests whose client-visible output carried dialect residue
 * (the drift alarm), eviction-safe like `total_requests`.
 */
dialect_residue_total: number, 
/**
 * Turns whose tool call failed schema validation and was re-issued with
 * `tool_choice: "required"`, counted whether or not the re-issue worked.
 *
 * A sustained non-zero rate says this model's `auto` path is
 * unconstrained upstream — the per-model signal ADR 0002 could otherwise
 * only read from a `--verbose` llama-server log.
 */
tool_repairs_attempted: number, 
/**
 * Of those, the ones that produced a conformant call. The ratio is the
 * number worth watching.
 */
tool_repairs_succeeded: number, 
/**
 * Upstream-degradation watchdog counters (empty responses, first-byte
 * timeouts, proactive recycles) since the proxy started.
 */
upstream_health: UpstreamHealthSnapshot, 
/**
 * Per-model defect counts, keyed by the model name requests carry.
 *
 * The fleet totals above answer "is something wrong"; this answers
 * "with which model", which is the only form the answer is actionable
 * in — a rate is a claim about a model, not about traffic.
 *
 * Process-lifetime and reset on restart, deliberately (ADR 0006): a
 * defect rate is a claim about *recent* traffic on *this* build.
 */
per_model_defects: { [key in string]: ModelDefectCounts }, 
/**
 * How prompt caching is configured for the running model. `None` until
 * the first request resolves a model, since the RAM budget isn't known
 * until something is launched.
 */
cache: CacheStatus | null, 
/**
 * Prompt-cache reuse for the in-process **agent path** — GUI
 * chat, which talk to llama-server directly rather than through
 * [`crate::forward`]. Reported as a separate population from [`Self::cache`]'s
 * `usage`, never merged into it: an agent turn's many small tool-driven calls
 * have a reuse profile nothing like a user's conversation. Top-level rather
 * than nested under [`Self::cache`] because it does not depend on the
 * proxy's cache configuration and must surface even before a proxied
 * request has resolved a model.
 */
agent_usage: CacheUsage, 
/**
 * What the running model's launch decided, and why — the same record the
 * CLI banner prints at startup (see
 * [`gglib_core::domain::LaunchNarration`]). `None` until a request has
 * resolved a model, since nothing has been launched to explain.
 */
launch: LaunchNarration | null, 
/**
 * Which models hold VRAM slots, what is queued behind them, and why the
 * second slot is or is not in use.
 *
 * Read live from the runtime on every snapshot rather than cached the way
 * [`Self::cache`] and [`Self::launch`] are. Those two change only when a
 * model is launched, so a write-on-resolution cache reports them
 * faithfully; queue depth changes continuously and without any request
 * resolving a model, so a cached copy would be wrong precisely when it
 * mattered — while traffic was backing up.
 */
admission: AdmissionSnapshot, 
/**
 * Whether the sampling gglib resolved is the sampling llama-server
 * applied — and, first, whether anyone is in a position to know.
 *
 * The Tier C organ ADR 0001 says makes the other tiers honest, and which
 * sampling did not have. Consumers must render
 * [`AuditState::Blind`](crate::sampling_audit::AuditState::Blind)
 * differently from `Comparing { divergences: 0 }`: a silent instrument
 * and a healthy one produce the same number and mean opposite things.
 *
 * It also carries the two records that are *not* comparisons, because
 * nothing on the wire echoes their subject: the reasoning controls
 * ([`ReasoningReadback`](crate::audit_records::ReasoningReadback), with the
 * running template's tri-state answer on `reasoning_effort`) and the client
 * field names the trust gate dropped. They ride here rather than beside
 * this field because the same store owns both the `/props` reading and the
 * resolved record — a peer field would need a second handle to it, and two
 * handles to one store are two things to keep in step.
 */
sampling_audit: SamplingAuditSnapshot, };
