// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the running model's template reads `reasoning_effort`, as three
 * states that are never collapsed into two.
 *
 * [`TemplateCapsState`]'s discipline carried one level up, and the reason it
 * is a type rather than an `Option<bool>`: "the template does not read it" and
 * "nobody has looked yet" license opposite actions. The first is what the
 * suppression gate acts on; the second must never be, and a surface that
 * renders them the same way has re-introduced exactly the collapse ADR 0007
 * decision 3 forbids.
 *
 * Three distinct causes fold into [`Self::NotYetObserved`] — no read yet, a
 * read that failed, and a caps object that did not carry the field — so each
 * carries its own reason rather than sharing a label.
 */
export type EffortSupportState = { "state": "supported" } | { "state": "not_supported" } | { "state": "not_yet_observed", 
/**
 * Which of the three causes applies, in words a dashboard can show.
 */
reason: string, };
