// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuppressedEffortRecord } from "./SuppressedEffortRecord";

/**
 * What the effort gate has thrown away since this proxy started.
 *
 * # Why the audit is where this lands
 *
 * Every other consumer of a request's sampling can re-derive its subject from
 * something. This one cannot: a suppressed `reasoning_effort` leaves **no
 * trace anywhere else in the system**. It is deleted from the body before the
 * request is sent, and neither reasoning control is echoed by `/slots.params`
 * or `/props` (ADR 0007 finding 7a), so the readback that catches every other
 * transmission fault is permanently blind to this one. That makes it Tier C's
 * business by elimination — it is an observation about gglib's own behaviour
 * that nothing else is positioned to make — and it is the reason the record is
 * kept at all rather than left to a `debug!` line an operator has to have been
 * running at the time to see.
 *
 * # Zero is not "nothing was suppressed"
 *
 * [`AuditState`]'s rule again. `requests: 0` is the honest reading on a model
 * whose template reads the variable, on a model nobody has probed, and on a
 * proxy that has served no request at all — three states with different
 * meanings. A surface rendering this must say what it is beside, not present
 * the count alone.
 */
export type EffortSuppressions = { 
/**
 * Requests on which a resolved level was deleted before sending.
 */
requests: number, 
/**
 * The most recent suppression, or `None` if there has been none.
 *
 * The most recent rather than a list, for the reason
 * [`PublishedOverrideField`] gives: with `trust_client_sampling` off every
 * request against one model and profile resolves identically, so a list
 * would be the same entry repeated. [`Self::requests`] is what says how
 * often.
 */
latest: SuppressedEffortRecord | null, };
