// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchDecision } from "./LaunchDecision";

/**
 * Everything the runtime decided for one llama-server launch.
 *
 * Built at spawn by the runtime; consumed by the CLI banner, the proxy
 * status endpoint, and the GUI dashboard. See the [module docs](self) for
 * why the decisions are an ordered list rather than named fields: the three
 * consumers all render the same rows in the same order, and a list keeps
 * adding a decision to a single site instead of four.
 */
export type LaunchNarration = { 
/**
 * Model name as the catalog knows it.
 */
model_name: string, 
/**
 * Quantization label (`Q4_K_M`), when the catalog recorded one.
 */
quantization: string | null, 
/**
 * On-disk weight size in bytes, summed across shards. `0` when unknown —
 * rendered as absent rather than as "0 GiB".
 */
weights_bytes: number, 
/**
 * The decisions, in the order they should be displayed.
 */
decisions: Array<LaunchDecision>, };
