// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One published field and what gglib's most recent intent did with it.
 *
 * The most recent rather than an aggregate, because with
 * `trust_client_sampling` off every request against one model and profile
 * resolves identically — the same property [ADR 0004] finding 4 relies on for
 * attribution. [`PublishedOverrides::intents`] is what says whether that
 * premise held.
 *
 * [ADR 0004]: https://github.com/mmogr/gglib/blob/main/docs/adr/0004-observe-the-sampling-boundary.md
 */
export type PublishedOverrideField = { 
/**
 * gglib's wire name for the parameter.
 */
field: string, 
/**
 * The GGUF key carrying it, e.g. `general.sampling.penalty_repeat`.
 */
key: string, } & ({ "state": "deferred", 
/**
 * What the sampler will use.
 */
published: number, } | { "state": "restated", 
/**
 * The value both sides name.
 */
published: number, } | { "state": "overridden", 
/**
 * What the model author published.
 */
published: number, 
/**
 * What gglib puts on the wire instead.
 */
sending: number, } | { "state": "unreadable" });
