// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Requests waiting for one model that is not currently resident.
 */
export type QueuedModelSnapshot = { 
/**
 * The model they are waiting for.
 */
model_name: string, 
/**
 * How many requests are queued.
 */
waiting: number, 
/**
 * Age of the oldest waiter, in milliseconds. A figure that keeps climbing
 * is the sign of a model that never goes idle long enough to be swapped
 * out — see the runtime's `admission` module for why that is bounded by a
 * deadline rather than by preemption.
 */
oldest_wait_ms: number, };
