// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffortSupportState } from "./EffortSupportState";
import type { ResolvedReasoning } from "./ResolvedReasoning";

/**
 * Everything a surface needs to render the reasoning controls honestly.
 */
export type ReasoningReadback = { 
/**
 * Whether the running model's template reads `reasoning_effort`.
 */
effort_support: EffortSupportState, 
/**
 * What the most recent resolved request named. `None` until one has been.
 */
latest: ResolvedReasoning | null, 
/**
 * [`WIRE_BLIND_REASON`], so every surface says the same thing.
 */
wire_blind_reason: string, };
