// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditState } from "./AuditState";
import type { BaselineState } from "./BaselineState";
import type { ClientFieldNames } from "./ClientFieldNames";
import type { Divergence } from "./Divergence";
import type { EffortSuppressions } from "./EffortSuppressions";
import type { PublishedOverrides } from "./PublishedOverrides";
import type { ReasoningReadback } from "./ReasoningReadback";

/**
 * Serializable view of [`SamplingAuditStore`], carried on the dashboard
 * snapshot.
 */
export type SamplingAuditSnapshot = { 
/**
 * Whether the organ is observing, blind, or simply has not seen a
 * request yet. Never collapse this to its counts when rendering.
 */
state: AuditState, 
/**
 * Polls that saw slots but could not attribute them to one intent.
 *
 * Beside the state rather than inside it: [`AuditState`] answers "can
 * this organ see", and abstaining is something an organ that *can* see
 * does. A large count here next to zero comparisons means the traffic is
 * too heterogeneous to attribute, which is a different problem from
 * blindness and wants a different fix.
 */
skipped_ambiguous: number, 
/**
 * Client sampling fields that could not be read as sent.
 */
client_fields_rejected: number, 
/**
 * Client sampling fields dropped by the trust gate.
 */
client_fields_discarded: number, 
/**
 * Most recent field-level disagreements, oldest first.
 */
recent_divergences: Array<Divergence>, 
/**
 * The `/props` baseline reading for the running model. See
 * [`crate::props`] — this is the half that catches a pin bump.
 *
 * Carries its own three states rather than being an `Option`, so a read
 * that failed cannot render as one that has not happened yet.
 */
baseline: BaselineState, 
/**
 * What gglib's own requests do with the running model's published
 * sampler defaults.
 */
published: PublishedOverrides, 
/**
 * Resolved `reasoning_effort` levels stage 5b deleted before sending.
 *
 * The one thing on this snapshot that no wire observation could ever
 * corroborate — see [`EffortSuppressions`].
 */
effort_suppressed: EffortSuppressions, 
/**
 * The two reasoning controls: what the template says about them, what the
 * last request resolved, and why none of it is an observation.
 *
 * Structurally different from every other field here. The rest of this
 * snapshot reports a comparison between gglib's intent and llama-server's
 * echo; there is no echo for these two (see the module docs), so this is
 * gglib's own account, carried with
 * [`WIRE_BLIND_REASON`] so no
 * surface can render it as a confirmed reading.
 */
reasoning: ReasoningReadback, 
/**
 * Which client field names were dropped, and how often each.
 *
 * [`Self::client_fields_discarded`] is the total; this is what it was made
 * of. Bounded — see [`crate::audit_records`].
 */
client_field_names: ClientFieldNames, };
