// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextTokenField } from "./NextTokenField";
import type { SlotParams } from "./SlotParams";

/**
 * One llama-server processing slot, as reported by `GET /slots`.
 *
 * Only the fields the proxy dashboard needs are modeled here. See the
 * module-level documentation for why `Option<T>` + `#[serde(default)]` is
 * used throughout instead of a raw [`serde_json::Value`].
 */
export type SlotSnapshot = { 
/**
 * Slot index within the running llama-server (`"id"` in the response).
 */
id: number, 
/**
 * ID of the task currently occupying this slot. Absent/`-1` means idle,
 * depending on llama.cpp version; kept as-is (no normalization).
 */
id_task: number | null, 
/**
 * Context size configured for this slot, in tokens.
 */
n_ctx: number | null, 
/**
 * Whether this slot is actively processing a request right now.
 */
is_processing: boolean, 
/**
 * The sampler settings llama-server parsed for the request in this
 * slot, when one is in flight.
 *
 * `None` on an idle slot — llama.cpp omits the whole object rather than
 * reporting the previous request's values, which is convenient: there
 * are no stale readings to guard against. See
 * [`crate::sampling_audit`].
 */
params: SlotParams | null, 
/**
 * Legacy field (older llama.cpp versions): tokens already resident in
 * this slot's KV cache. Superseded by `n_prompt_tokens`/`next_token` in
 * current upstream versions, where it is simply absent — kept only as
 * a best-effort fallback, see [`Self::tokens_in_use`].
 */
n_past: number | null, 
/**
 * Alternate legacy field name seen in some intermediate llama.cpp
 * builds; same role as `n_past`.
 */
cache_tokens: number | null, 
/**
 * Current-schema field: total token count of the prompt currently
 * loaded into this slot (the "prompt half" of context usage, as
 * opposed to `next_token.n_decoded`'s generated-token count).
 */
n_prompt_tokens: number | null, 
/**
 * Current-schema field: how many of `n_prompt_tokens` have actually
 * been processed (prefilled) so far, i.e. run through the model this
 * round — this is a *delta*, excluding anything reused from cache.
 * Preferred over `n_prompt_tokens` itself when present, since it
 * tracks real progress during an in-flight prefill rather than the
 * eventual total; must be combined with `n_prompt_tokens_cache` to
 * recover the true total prompt usage, see [`Self::tokens_in_use`].
 */
n_prompt_tokens_processed: number | null, 
/**
 * Current-schema field: number of prompt tokens reused from KV cache
 * (prefix-match reuse across requests to the same slot), i.e. *not*
 * re-run through the model this round. Mirrors the `cache_n` field in
 * the `/v1/chat/completions` response's `timings` object, where
 * llama.cpp documents the invariant `prompt_n + cache_n + predicted_n`
 * as the total tokens in context — only meaningful alongside
 * `n_prompt_tokens_processed` (the `prompt_n` analogue); adding it to
 * the grand-total `n_prompt_tokens` fallback would double-count.
 */
n_prompt_tokens_cache: number | null, 
/**
 * Current-schema nested object carrying generation progress. We only
 * need `n_decoded` out of it — the count of tokens generated so far,
 * which is additive with `n_prompt_tokens(_processed)` to get total
 * context usage, see [`Self::tokens_in_use`].
 *
 * On llama.cpp builds with Multi-Token Prediction ("draft-mtp")
 * enabled, upstream sends this as a JSON **array** of objects (one per
 * predicted token) instead of a single object — see [`NextTokenField`].
 */
next_token: NextTokenField | null, };
