// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";

/**
 * One resolved `reasoning_effort` stage 5b deleted, in a form a surface can
 * render.
 *
 * [`SuppressedEffort`] carries the rung as a [`ParamSource`], whose
 * `Layer(i)` indexes a ladder no reader of a JSON snapshot has. Resolved to
 * the rung's name here, at the one point where
 * [`SamplingDecision::layer_names`] is still in hand.
 */
export type SuppressedEffortRecord = { 
/**
 * The level the ladder resolved and llama-server never saw.
 */
level: ReasoningEffort, 
/**
 * The rung that asked for it — `profile`, `model`, `global`, `cli`.
 */
source: string, };
