import { useState, useEffect, useRef, useCallback } from 'react';
import { useConfirmContext } from '../../../contexts/ConfirmContext';
import { appLogger } from '../../../services/platform';
import type { ToastType } from '../../Toast';
import { getTransport } from '../../../services/transport';
import type { ConversationSummary } from '../../../services/transport';
import type { RunInfo } from '../../../types/generated/RunInfo';

/** Whether `conversation` still has the title a chat is made with. */
const hasDefaultTitle = (conversation: ConversationSummary) =>
  conversation.title === 'New Chat' || !conversation.title;

/**
 * Options for the useTitleGeneration hook.
 */
export interface UseTitleGenerationOptions {
  /** The run the page last read to its end, as it ended. */
  endedRun: RunInfo | null;
  /** Currently active conversation */
  activeConversation: ConversationSummary | null;
  /** Currently active conversation ID */
  activeConversationId: number | null;
  /** Server port for AI title generation; absent when the chat is remote. */
  serverPort?: number;
  /** Prompt template for title generation */
  titleGenerationPrompt: string;
  /** Callback to rename conversation */
  onRenameConversation: (title: string) => Promise<void>;
  /** Toast notification function */
  showToast: (message: string, type?: ToastType, duration?: number) => void;
}

/**
 * Result returned by useTitleGeneration.
 */
export interface UseTitleGenerationResult {
  /** Current title draft (for editing) */
  titleDraft: string;
  /** Update title draft */
  setTitleDraft: (title: string) => void;
  /** Whether rename input is visible */
  isRenaming: boolean;
  /** Start rename mode */
  startRenaming: () => void;
  /** Cancel rename mode */
  cancelRenaming: () => void;
  /** Commit the rename */
  commitRename: () => Promise<void>;
  /** Whether AI title generation is in progress */
  isGeneratingTitle: boolean;
  /** Trigger AI title generation */
  generateTitle: () => Promise<void>;
}

/**
 * Hook for managing conversation title editing and AI generation.
 * 
 * Responsibilities:
 * - Manages title draft state for inline editing
 * - Handles rename commit/cancel
 * - Asks for a title by itself when the first reply finishes in a chat still called by its default title
 * - Manual AI title generation with confirmation
 */
export function useTitleGeneration({
  endedRun,
  activeConversation,
  activeConversationId,
  serverPort,
  titleGenerationPrompt,
  onRenameConversation,
  showToast,
}: UseTitleGenerationOptions): UseTitleGenerationResult {
  const [titleDraft, setTitleDraft] = useState('');
  const [isRenaming, setIsRenaming] = useState(false);
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);
  const hasAutoGeneratedTitleRef = useRef(false);
  const { confirm } = useConfirmContext();

  // Sync title draft with active conversation
  useEffect(() => {
    if (activeConversation && !isRenaming) {
      setTitleDraft(activeConversation.title);
    }
  }, [activeConversation, isRenaming]);

  // Reset state when conversation changes
  useEffect(() => {
    setIsGeneratingTitle(false);
    hasAutoGeneratedTitleRef.current = false;
  }, [activeConversationId]);

  const startRenaming = useCallback(() => {
    setIsRenaming(true);
  }, []);

  const cancelRenaming = useCallback(() => {
    setIsRenaming(false);
    setTitleDraft(activeConversation?.title ?? '');
  }, [activeConversation?.title]);

  const commitRename = useCallback(async () => {
    if (!titleDraft.trim()) {
      setIsRenaming(false);
      setTitleDraft(activeConversation?.title ?? '');
      return;
    }
    await onRenameConversation(titleDraft.trim());
    setIsRenaming(false);
  }, [titleDraft, activeConversation?.title, onRenameConversation]);

  // Generate chat title using AI
  const generateTitle = useCallback(async () => {
    // Early return if no active conversation ID - prevents errors during state transitions
    if (!activeConversationId) {
      showToast('No active conversation', 'warning');
      return;
    }

    if (!activeConversation || !serverPort) return;

    // Show confirmation if overwriting an existing non-default title
    if (!hasDefaultTitle(activeConversation)) {
      const confirmed = await confirm({
        title: 'Replace conversation title?',
        description: 'The current title will be replaced with an AI-generated one.',
        confirmLabel: 'Replace',
      });
      if (!confirmed) return;
    }

    setIsGeneratingTitle(true);
    try {
      // Fetch fresh messages from the database
      const { messages } = await getTransport().getThread(activeConversationId);
      
      if (messages.length === 0) {
        showToast('Cannot generate title for empty conversation', 'warning');
        return;
      }

      const generatedTitle = await getTransport().generateChatTitle({
        serverPort,
        messages,
        prompt: titleGenerationPrompt,
      });

      await onRenameConversation(generatedTitle);
      showToast('Title generated successfully', 'success');
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to generate title';
      showToast(message, 'error');
      appLogger.error('hook.ui', 'Title generation failed', { error, conversationId: activeConversationId });
    } finally {
      setIsGeneratingTitle(false);
    }
  }, [activeConversation, activeConversationId, serverPort, titleGenerationPrompt, onRenameConversation, showToast, confirm]);

  // The first reply to finish while the chat is open titles it, if it is
  // still called by its default title then: a run of this chat that the page
  // read to its end and the daemon ended `completed`, its reply saved. The
  // title is weighed at that one moment. A chat that is only opened has no
  // such run, whatever it already holds.
  useEffect(() => {
    if (hasAutoGeneratedTitleRef.current || !activeConversation) return;
    if (endedRun?.status !== 'completed' || endedRun.conversation_id !== activeConversation.id) return;
    hasAutoGeneratedTitleRef.current = true;
    if (hasDefaultTitle(activeConversation)) void generateTitle();
  }, [endedRun, activeConversation, generateTitle]);

  return {
    titleDraft,
    setTitleDraft,
    isRenaming,
    startRenaming,
    cancelRenaming,
    commitRename,
    isGeneratingTitle,
    generateTitle,
  };
}
